defmodule Fhir.v6().ActivityDefinition do
  use TypedStruct

  typedstruct do
    field(:_approvalDate, Fhir.v6().Element)
    field(:_asNeededBoolean, Fhir.v6().Element)
    field(:_copyright, Fhir.v6().Element)
    field(:_copyrightLabel, Fhir.v6().Element)
    field(:_date, Fhir.v6().Element)
    field(:_description, Fhir.v6().Element)
    field(:_doNotPerform, Fhir.v6().Element)
    field(:_experimental, Fhir.v6().Element)
    field(:_implicitRules, Fhir.v6().Element)
    field(:_intent, Fhir.v6().Element)
    field(:_kind, Fhir.v6().Element)
    field(:_language, Fhir.v6().Element)
    field(:_lastReviewDate, Fhir.v6().Element)
    field(:_name, Fhir.v6().Element)
    field(:_priority, Fhir.v6().Element)
    field(:_publisher, Fhir.v6().Element)
    field(:_purpose, Fhir.v6().Element)
    field(:_status, Fhir.v6().Element)
    field(:_subjectCanonical, Fhir.v6().Element)
    field(:_subtitle, Fhir.v6().Element)
    field(:_title, Fhir.v6().Element)
    field(:_url, Fhir.v6().Element)
    field(:_usage, Fhir.v6().Element)
    field(:_version, Fhir.v6().Element)
    field(:_versionAlgorithmString, Fhir.v6().Element)
    field(:approvalDate, :date)
    field(:asNeededBoolean, :boolean)
    field(:asNeededCodeableConcept, Fhir.v6().CodeableConcept)
    field(:author, [Fhir.v6().ContactDetail], default: [])
    field(:bodySite, [Fhir.v6().CodeableConcept], default: [])
    field(:code, Fhir.v6().CodeableConcept)
    field(:contact, [Fhir.v6().ContactDetail], default: [])
    field(:contained, [Fhir.v6().ResourceList], default: [])
    field(:copyright, :string)
    field(:copyrightLabel, :string)
    field(:date, :datetime)
    field(:description, :string)
    field(:doNotPerform, :boolean)
    field(:dosage, [Fhir.v6().Dosage], default: [])
    field(:dynamicValue, [Fhir.v6().ActivityDefinitionDynamicValue], default: [])
    field(:editor, [Fhir.v6().ContactDetail], default: [])
    field(:effectivePeriod, Fhir.v6().Period)
    field(:endorser, [Fhir.v6().ContactDetail], default: [])
    field(:experimental, :boolean)
    field(:extension, [Fhir.v6().Extension], default: [])
    field(:id, :string)
    field(:identifier, [Fhir.v6().Identifier], default: [])
    field(:implicitRules, :string)
    field(:intent, :string)
    field(:jurisdiction, [Fhir.v6().CodeableConcept], default: [])
    field(:kind, :string)
    field(:language, :string)
    field(:lastReviewDate, :date)
    field(:library, [:string], default: [])
    field(:location, Fhir.v6().CodeableReference)
    field(:meta, Fhir.v6().Meta)
    field(:modifierExtension, [Fhir.v6().Extension], default: [])
    field(:name, :string)
    field(:observationRequirement, [:string], default: [])
    field(:observationResultRequirement, [:string], default: [])
    field(:participant, [Fhir.v6().ActivityDefinitionParticipant], default: [])
    field(:priority, :string)
    field(:productCodeableConcept, Fhir.v6().CodeableConcept)
    field(:productReference, Fhir.v6().Reference)
    field(:profile, :string)
    field(:publisher, :string)
    field(:purpose, :string)
    field(:quantity, Fhir.v6().Quantity)
    field(:relatedArtifact, [Fhir.v6().RelatedArtifact], default: [])
    field(:resourceType, :string, default: "ActivityDefinition")
    field(:reviewer, [Fhir.v6().ContactDetail], default: [])
    field(:specimenRequirement, [:string], default: [])
    field(:status, :string)
    field(:subjectCanonical, :string)
    field(:subjectCodeableConcept, Fhir.v6().CodeableConcept)
    field(:subjectReference, Fhir.v6().Reference)
    field(:subtitle, :string)
    field(:text, Fhir.v6().Narrative)
    field(:timingAge, Fhir.v6().Age)
    field(:timingDuration, Fhir.v6().Duration)
    field(:timingRange, Fhir.v6().Range)
    field(:timingTiming, Fhir.v6().Timing)
    field(:title, :string)
    field(:topic, [Fhir.v6().CodeableConcept], default: [])
    field(:transform, :string)
    field(:url, :string)
    field(:usage, :string)
    field(:useContext, [Fhir.v6().UsageContext], default: [])
    field(:version, :string)
    field(:versionAlgorithmCoding, Fhir.v6().Coding)
    field(:versionAlgorithmString, :string)
  end
end
