defmodule Fhir.v6().AdverseEvent do
  use TypedStruct

  typedstruct do
    field(:_actuality, Fhir.v6().Element)
    field(:_detected, Fhir.v6().Element)
    field(:_expectedInResearchStudy, Fhir.v6().Element)
    field(:_implicitRules, Fhir.v6().Element)
    field(:_language, Fhir.v6().Element)
    field(:_occurrenceDateTime, Fhir.v6().Element)
    field(:_recordedDate, Fhir.v6().Element)
    field(:_status, Fhir.v6().Element)
    field(:actuality, :string)
    field(:category, [Fhir.v6().CodeableConcept], default: [])
    field(:code, Fhir.v6().CodeableConcept)
    field(:contained, [Fhir.v6().ResourceList], default: [])
    field(:contributingFactor, [Fhir.v6().AdverseEventContributingFactor], default: [])
    field(:detected, :datetime)
    field(:encounter, Fhir.v6().Reference)
    field(:expectedInResearchStudy, :boolean)
    field(:extension, [Fhir.v6().Extension], default: [])
    field(:id, :string)
    field(:identifier, [Fhir.v6().Identifier], default: [])
    field(:implicitRules, :string)
    field(:language, :string)
    field(:location, Fhir.v6().Reference)
    field(:meta, Fhir.v6().Meta)
    field(:mitigatingAction, [Fhir.v6().AdverseEventMitigatingAction], default: [])
    field(:modifierExtension, [Fhir.v6().Extension], default: [])
    field(:note, [Fhir.v6().Annotation], default: [])
    field(:occurrenceDateTime, :string)
    field(:occurrencePeriod, Fhir.v6().Period)
    field(:occurrenceTiming, Fhir.v6().Timing)
    field(:outcome, [Fhir.v6().CodeableConcept], default: [])
    field(:participant, [Fhir.v6().AdverseEventParticipant], default: [])
    field(:preventiveAction, [Fhir.v6().AdverseEventPreventiveAction], default: [])
    field(:recordedDate, :datetime)
    field(:recorder, Fhir.v6().Reference)
    field(:resourceType, :string, default: "AdverseEvent")
    field(:resultingEffect, [Fhir.v6().Reference], default: [])
    field(:seriousness, Fhir.v6().CodeableConcept)
    field(:status, :string)
    field(:study, [Fhir.v6().Reference], default: [])
    field(:subject, Fhir.v6().Reference)
    field(:supportingInfo, [Fhir.v6().AdverseEventSupportingInfo], default: [])
    field(:suspectEntity, [Fhir.v6().AdverseEventSuspectEntity], default: [])
    field(:text, Fhir.v6().Narrative)
  end
end
