defmodule Fhir.v6().AllergyIntolerance do
  use TypedStruct

  typedstruct do
    field(:_category, [Fhir.v6().Element], default: [])
    field(:_criticality, Fhir.v6().Element)
    field(:_implicitRules, Fhir.v6().Element)
    field(:_language, Fhir.v6().Element)
    field(:_lastOccurrence, Fhir.v6().Element)
    field(:_onsetDateTime, Fhir.v6().Element)
    field(:_onsetString, Fhir.v6().Element)
    field(:_recordedDate, Fhir.v6().Element)
    field(:category, [:string], default: [])
    field(:clinicalStatus, Fhir.v6().CodeableConcept)
    field(:code, Fhir.v6().CodeableConcept)
    field(:contained, [Fhir.v6().ResourceList], default: [])
    field(:criticality, :string)
    field(:encounter, Fhir.v6().Reference)
    field(:extension, [Fhir.v6().Extension], default: [])
    field(:id, :string)
    field(:identifier, [Fhir.v6().Identifier], default: [])
    field(:implicitRules, :string)
    field(:language, :string)
    field(:lastOccurrence, :datetime)
    field(:meta, Fhir.v6().Meta)
    field(:modifierExtension, [Fhir.v6().Extension], default: [])
    field(:note, [Fhir.v6().Annotation], default: [])
    field(:onsetAge, Fhir.v6().Age)
    field(:onsetDateTime, :string)
    field(:onsetPeriod, Fhir.v6().Period)
    field(:onsetRange, Fhir.v6().Range)
    field(:onsetString, :string)
    field(:participant, [Fhir.v6().AllergyIntoleranceParticipant], default: [])
    field(:patient, Fhir.v6().Reference)
    field(:reaction, [Fhir.v6().AllergyIntoleranceReaction], default: [])
    field(:recordedDate, :datetime)
    field(:resourceType, :string, default: "AllergyIntolerance")
    field(:text, Fhir.v6().Narrative)
    field(:type, Fhir.v6().CodeableConcept)
    field(:verificationStatus, Fhir.v6().CodeableConcept)
  end
end
