defmodule Fhir.v6().Appointment do
  use TypedStruct

  typedstruct do
    field(:_cancellationDate, Fhir.v6().Element)
    field(:_created, Fhir.v6().Element)
    field(:_description, Fhir.v6().Element)
    field(:_end, Fhir.v6().Element)
    field(:_implicitRules, Fhir.v6().Element)
    field(:_language, Fhir.v6().Element)
    field(:_minutesDuration, Fhir.v6().Element)
    field(:_occurrenceChanged, Fhir.v6().Element)
    field(:_recurrenceId, Fhir.v6().Element)
    field(:_start, Fhir.v6().Element)
    field(:_status, Fhir.v6().Element)
    field(:account, [Fhir.v6().Reference], default: [])
    field(:appointmentType, Fhir.v6().CodeableConcept)
    field(:basedOn, [Fhir.v6().Reference], default: [])
    field(:cancellationDate, :datetime)
    field(:cancellationReason, Fhir.v6().CodeableConcept)
    field(:class, [Fhir.v6().CodeableConcept], default: [])
    field(:contained, [Fhir.v6().ResourceList], default: [])
    field(:created, :datetime)
    field(:description, :string)
    field(:end, :timestamp)
    field(:extension, [Fhir.v6().Extension], default: [])
    field(:id, :string)
    field(:identifier, [Fhir.v6().Identifier], default: [])
    field(:implicitRules, :string)
    field(:language, :string)
    field(:meta, Fhir.v6().Meta)
    field(:minutesDuration, :float)
    field(:modifierExtension, [Fhir.v6().Extension], default: [])
    field(:note, [Fhir.v6().Annotation], default: [])
    field(:occurrenceChanged, :boolean)
    field(:originatingAppointment, Fhir.v6().Reference)
    field(:participant, [Fhir.v6().AppointmentParticipant], default: [])
    field(:patientInstruction, [Fhir.v6().CodeableReference], default: [])
    field(:previousAppointment, Fhir.v6().Reference)
    field(:priority, Fhir.v6().CodeableConcept)
    field(:reason, [Fhir.v6().CodeableReference], default: [])
    field(:recurrenceId, :float)
    field(:recurrenceTemplate, [Fhir.v6().AppointmentRecurrenceTemplate], default: [])
    field(:replaces, [Fhir.v6().Reference], default: [])
    field(:requestedPeriod, [Fhir.v6().Period], default: [])
    field(:resourceType, :string, default: "Appointment")
    field(:serviceCategory, [Fhir.v6().CodeableConcept], default: [])
    field(:serviceType, [Fhir.v6().CodeableReference], default: [])
    field(:slot, [Fhir.v6().Reference], default: [])
    field(:specialty, [Fhir.v6().CodeableConcept], default: [])
    field(:start, :timestamp)
    field(:status, :string)
    field(:subject, Fhir.v6().Reference)
    field(:supportingInformation, [Fhir.v6().Reference], default: [])
    field(:text, Fhir.v6().Narrative)
    field(:virtualService, [Fhir.v6().VirtualServiceDetail], default: [])
  end
end
