defmodule Fhir.v6().ArtifactAssessment do
  use TypedStruct

  typedstruct do
    field(:_approvalDate, Fhir.v6().Element)
    field(:_artifactCanonical, Fhir.v6().Element)
    field(:_artifactUri, Fhir.v6().Element)
    field(:_citeAsMarkdown, Fhir.v6().Element)
    field(:_copyright, Fhir.v6().Element)
    field(:_date, Fhir.v6().Element)
    field(:_disposition, Fhir.v6().Element)
    field(:_implicitRules, Fhir.v6().Element)
    field(:_language, Fhir.v6().Element)
    field(:_lastReviewDate, Fhir.v6().Element)
    field(:_title, Fhir.v6().Element)
    field(:_workflowStatus, Fhir.v6().Element)
    field(:approvalDate, :date)
    field(:artifactCanonical, :string)
    field(:artifactReference, Fhir.v6().Reference)
    field(:artifactUri, :string)
    field(:citeAsMarkdown, :string)
    field(:citeAsReference, Fhir.v6().Reference)
    field(:contained, [Fhir.v6().ResourceList], default: [])
    field(:content, [Fhir.v6().ArtifactAssessmentContent], default: [])
    field(:copyright, :string)
    field(:date, :datetime)
    field(:disposition, :string)
    field(:extension, [Fhir.v6().Extension], default: [])
    field(:id, :string)
    field(:identifier, [Fhir.v6().Identifier], default: [])
    field(:implicitRules, :string)
    field(:language, :string)
    field(:lastReviewDate, :date)
    field(:meta, Fhir.v6().Meta)
    field(:modifierExtension, [Fhir.v6().Extension], default: [])
    field(:resourceType, :string, default: "ArtifactAssessment")
    field(:text, Fhir.v6().Narrative)
    field(:title, :string)
    field(:workflowStatus, :string)
  end
end
