defmodule Fhir.v6().AuditEvent do
  use TypedStruct

  typedstruct do
    field(:_action, Fhir.v6().Element)
    field(:_implicitRules, Fhir.v6().Element)
    field(:_language, Fhir.v6().Element)
    field(:_occurredDateTime, Fhir.v6().Element)
    field(:_recorded, Fhir.v6().Element)
    field(:_severity, Fhir.v6().Element)
    field(:action, :string)
    field(:agent, [Fhir.v6().AuditEventAgent], default: [])
    field(:authorization, [Fhir.v6().CodeableConcept], default: [])
    field(:basedOn, [Fhir.v6().Reference], default: [])
    field(:category, [Fhir.v6().CodeableConcept], default: [])
    field(:code, Fhir.v6().CodeableConcept)
    field(:contained, [Fhir.v6().ResourceList], default: [])
    field(:encounter, Fhir.v6().Reference)
    field(:entity, [Fhir.v6().AuditEventEntity], default: [])
    field(:extension, [Fhir.v6().Extension], default: [])
    field(:id, :string)
    field(:implicitRules, :string)
    field(:language, :string)
    field(:meta, Fhir.v6().Meta)
    field(:modifierExtension, [Fhir.v6().Extension], default: [])
    field(:occurredDateTime, :string)
    field(:occurredPeriod, Fhir.v6().Period)
    field(:outcome, Fhir.v6().AuditEventOutcome)
    field(:patient, Fhir.v6().Reference)
    field(:recorded, :timestamp)
    field(:resourceType, :string, default: "AuditEvent")
    field(:severity, :string)
    field(:source, Fhir.v6().AuditEventSource)
    field(:text, Fhir.v6().Narrative)
  end
end
