defmodule Fhir.v6().BiologicallyDerivedProductDispense do
  use TypedStruct

  typedstruct do
    field(:_implicitRules, Fhir.v6().Element)
    field(:_language, Fhir.v6().Element)
    field(:_preparedDate, Fhir.v6().Element)
    field(:_status, Fhir.v6().Element)
    field(:_usageInstruction, Fhir.v6().Element)
    field(:_whenHandedOver, Fhir.v6().Element)
    field(:basedOn, [Fhir.v6().Reference], default: [])
    field(:contained, [Fhir.v6().ResourceList], default: [])
    field(:destination, Fhir.v6().Reference)
    field(:extension, [Fhir.v6().Extension], default: [])
    field(:id, :string)
    field(:identifier, [Fhir.v6().Identifier], default: [])
    field(:implicitRules, :string)
    field(:language, :string)
    field(:location, Fhir.v6().Reference)
    field(:matchStatus, Fhir.v6().CodeableConcept)
    field(:meta, Fhir.v6().Meta)
    field(:modifierExtension, [Fhir.v6().Extension], default: [])
    field(:note, [Fhir.v6().Annotation], default: [])
    field(:originRelationshipType, Fhir.v6().CodeableConcept)
    field(:partOf, [Fhir.v6().Reference], default: [])
    field(:patient, Fhir.v6().Reference)
    field(:performer, [Fhir.v6().BiologicallyDerivedProductDispensePerformer], default: [])
    field(:preparedDate, :datetime)
    field(:product, Fhir.v6().Reference)
    field(:quantity, Fhir.v6().Quantity)
    field(:resourceType, :string, default: "BiologicallyDerivedProductDispense")
    field(:status, :string)
    field(:text, Fhir.v6().Narrative)
    field(:usageInstruction, :string)
    field(:whenHandedOver, :datetime)
  end
end
