defmodule Fhir.v6().CapabilityStatementResource do
  use TypedStruct

  typedstruct do
    field(:_conditionalCreate, Fhir.v6().Element)
    field(:_conditionalDelete, Fhir.v6().Element)
    field(:_conditionalPatch, Fhir.v6().Element)
    field(:_conditionalRead, Fhir.v6().Element)
    field(:_conditionalUpdate, Fhir.v6().Element)
    field(:_documentation, Fhir.v6().Element)
    field(:_readHistory, Fhir.v6().Element)
    field(:_referencePolicy, [Fhir.v6().Element], default: [])
    field(:_searchInclude, [Fhir.v6().Element], default: [])
    field(:_searchRevInclude, [Fhir.v6().Element], default: [])
    field(:_type, Fhir.v6().Element)
    field(:_updateCreate, Fhir.v6().Element)
    field(:_versioning, Fhir.v6().Element)
    field(:conditionalCreate, :boolean)
    field(:conditionalDelete, :string)
    field(:conditionalPatch, :boolean)
    field(:conditionalRead, :string)
    field(:conditionalUpdate, :boolean)
    field(:documentation, :string)
    field(:extension, [Fhir.v6().Extension], default: [])
    field(:id, :string)
    field(:interaction, [Fhir.v6().CapabilityStatementInteraction], default: [])
    field(:modifierExtension, [Fhir.v6().Extension], default: [])
    field(:operation, [Fhir.v6().CapabilityStatementOperation], default: [])
    field(:profile, :string)
    field(:readHistory, :boolean)
    field(:referencePolicy, [:string], default: [])
    field(:searchInclude, [:string], default: [])
    field(:searchParam, [Fhir.v6().CapabilityStatementSearchParam], default: [])
    field(:searchRevInclude, [:string], default: [])
    field(:supportedProfile, [:string], default: [])
    field(:type, :string)
    field(:updateCreate, :boolean)
    field(:versioning, :string)
  end
end
