defmodule Fhir.v6().CapabilityStatement do
  use TypedStruct

  typedstruct do
    field(:_acceptLanguage, [Fhir.v6().Element], default: [])
    field(:_copyright, Fhir.v6().Element)
    field(:_copyrightLabel, Fhir.v6().Element)
    field(:_date, Fhir.v6().Element)
    field(:_description, Fhir.v6().Element)
    field(:_experimental, Fhir.v6().Element)
    field(:_fhirVersion, Fhir.v6().Element)
    field(:_format, [Fhir.v6().Element], default: [])
    field(:_implicitRules, Fhir.v6().Element)
    field(:_kind, Fhir.v6().Element)
    field(:_language, Fhir.v6().Element)
    field(:_name, Fhir.v6().Element)
    field(:_patchFormat, [Fhir.v6().Element], default: [])
    field(:_publisher, Fhir.v6().Element)
    field(:_purpose, Fhir.v6().Element)
    field(:_status, Fhir.v6().Element)
    field(:_title, Fhir.v6().Element)
    field(:_url, Fhir.v6().Element)
    field(:_version, Fhir.v6().Element)
    field(:_versionAlgorithmString, Fhir.v6().Element)
    field(:acceptLanguage, [:string], default: [])
    field(:contact, [Fhir.v6().ContactDetail], default: [])
    field(:contained, [Fhir.v6().ResourceList], default: [])
    field(:copyright, :string)
    field(:copyrightLabel, :string)
    field(:date, :datetime)
    field(:description, :string)
    field(:document, [Fhir.v6().CapabilityStatementDocument], default: [])
    field(:experimental, :boolean)
    field(:extension, [Fhir.v6().Extension], default: [])
    field(:fhirVersion, :string)
    field(:format, [:string], default: [])
    field(:id, :string)
    field(:identifier, [Fhir.v6().Identifier], default: [])
    field(:implementation, Fhir.v6().CapabilityStatementImplementation)
    field(:implementationGuide, [:string], default: [])
    field(:implicitRules, :string)
    field(:imports, [:string], default: [])
    field(:instantiates, [:string], default: [])
    field(:jurisdiction, [Fhir.v6().CodeableConcept], default: [])
    field(:kind, :string)
    field(:language, :string)
    field(:messaging, [Fhir.v6().CapabilityStatementMessaging], default: [])
    field(:meta, Fhir.v6().Meta)
    field(:modifierExtension, [Fhir.v6().Extension], default: [])
    field(:name, :string)
    field(:patchFormat, [:string], default: [])
    field(:publisher, :string)
    field(:purpose, :string)
    field(:resourceType, :string, default: "CapabilityStatement")
    field(:rest, [Fhir.v6().CapabilityStatementRest], default: [])
    field(:software, Fhir.v6().CapabilityStatementSoftware)
    field(:status, :string)
    field(:text, Fhir.v6().Narrative)
    field(:title, :string)
    field(:url, :string)
    field(:useContext, [Fhir.v6().UsageContext], default: [])
    field(:version, :string)
    field(:versionAlgorithmCoding, Fhir.v6().Coding)
    field(:versionAlgorithmString, :string)
  end
end
