defmodule Fhir.v6().ChargeItem do
  use TypedStruct

  typedstruct do
    field(:_definitionUri, [Fhir.v6().Element], default: [])
    field(:_enteredDate, Fhir.v6().Element)
    field(:_implicitRules, Fhir.v6().Element)
    field(:_language, Fhir.v6().Element)
    field(:_occurrenceDateTime, Fhir.v6().Element)
    field(:_status, Fhir.v6().Element)
    field(:account, [Fhir.v6().Reference], default: [])
    field(:bodysite, [Fhir.v6().CodeableConcept], default: [])
    field(:code, Fhir.v6().CodeableConcept)
    field(:contained, [Fhir.v6().ResourceList], default: [])
    field(:costCenter, Fhir.v6().Reference)
    field(:definitionCanonical, [:string], default: [])
    field(:definitionUri, [:string], default: [])
    field(:encounter, Fhir.v6().Reference)
    field(:enteredDate, :datetime)
    field(:enterer, Fhir.v6().Reference)
    field(:extension, [Fhir.v6().Extension], default: [])
    field(:id, :string)
    field(:identifier, [Fhir.v6().Identifier], default: [])
    field(:implicitRules, :string)
    field(:language, :string)
    field(:meta, Fhir.v6().Meta)
    field(:modifierExtension, [Fhir.v6().Extension], default: [])
    field(:note, [Fhir.v6().Annotation], default: [])
    field(:occurrenceDateTime, :string)
    field(:occurrencePeriod, Fhir.v6().Period)
    field(:occurrenceTiming, Fhir.v6().Timing)
    field(:overrideReason, Fhir.v6().CodeableConcept)
    field(:partOf, [Fhir.v6().Reference], default: [])
    field(:performer, [Fhir.v6().ChargeItemPerformer], default: [])
    field(:performingOrganization, Fhir.v6().Reference)
    field(:product, [Fhir.v6().CodeableReference], default: [])
    field(:quantity, Fhir.v6().Quantity)
    field(:reason, [Fhir.v6().CodeableConcept], default: [])
    field(:requestingOrganization, Fhir.v6().Reference)
    field(:resourceType, :string, default: "ChargeItem")
    field(:service, [Fhir.v6().CodeableReference], default: [])
    field(:status, :string)
    field(:subject, Fhir.v6().Reference)
    field(:supportingInformation, [Fhir.v6().Reference], default: [])
    field(:text, Fhir.v6().Narrative)
    field(:totalPriceComponent, Fhir.v6().MonetaryComponent)
    field(:unitPriceComponent, Fhir.v6().MonetaryComponent)
  end
end
