defmodule Fhir.v6().CitationPublicationForm do
  use TypedStruct

  typedstruct do
    field(:_accessionNumber, Fhir.v6().Element)
    field(:_articleDate, Fhir.v6().Element)
    field(:_copyright, Fhir.v6().Element)
    field(:_firstPage, Fhir.v6().Element)
    field(:_issue, Fhir.v6().Element)
    field(:_lastPage, Fhir.v6().Element)
    field(:_lastRevisionDate, Fhir.v6().Element)
    field(:_pageCount, Fhir.v6().Element)
    field(:_pageString, Fhir.v6().Element)
    field(:_publicationDateSeason, Fhir.v6().Element)
    field(:_publicationDateText, Fhir.v6().Element)
    field(:_volume, Fhir.v6().Element)
    field(:accessionNumber, :string)
    field(:articleDate, :datetime)
    field(:citedMedium, Fhir.v6().CodeableConcept)
    field(:copyright, :string)
    field(:extension, [Fhir.v6().Extension], default: [])
    field(:firstPage, :string)
    field(:id, :string)
    field(:issue, :string)
    field(:language, [Fhir.v6().CodeableConcept], default: [])
    field(:lastPage, :string)
    field(:lastRevisionDate, :datetime)
    field(:modifierExtension, [Fhir.v6().Extension], default: [])
    field(:pageCount, :string)
    field(:pageString, :string)
    field(:publicationDateSeason, :string)
    field(:publicationDateText, :string)
    field(:publishedIn, Fhir.v6().CitationPublishedIn)
    field(:volume, :string)
  end
end
