defmodule Fhir.v6().Claim do
  use TypedStruct

  typedstruct do
    field(:_created, Fhir.v6().Element)
    field(:_implicitRules, Fhir.v6().Element)
    field(:_language, Fhir.v6().Element)
    field(:_status, Fhir.v6().Element)
    field(:_use, Fhir.v6().Element)
    field(:accident, Fhir.v6().ClaimAccident)
    field(:billablePeriod, Fhir.v6().Period)
    field(:careTeam, [Fhir.v6().ClaimCareTeam], default: [])
    field(:contained, [Fhir.v6().ResourceList], default: [])
    field(:created, :datetime)
    field(:diagnosis, [Fhir.v6().ClaimDiagnosis], default: [])
    field(:diagnosisRelatedGroup, Fhir.v6().CodeableConcept)
    field(:encounter, [Fhir.v6().Reference], default: [])
    field(:enterer, Fhir.v6().Reference)
    field(:event, [Fhir.v6().ClaimEvent], default: [])
    field(:extension, [Fhir.v6().Extension], default: [])
    field(:facility, Fhir.v6().Reference)
    field(:fundsReserve, Fhir.v6().CodeableConcept)
    field(:id, :string)
    field(:identifier, [Fhir.v6().Identifier], default: [])
    field(:implicitRules, :string)
    field(:insurance, [Fhir.v6().ClaimInsurance], default: [])
    field(:insurer, Fhir.v6().Reference)
    field(:item, [Fhir.v6().ClaimItem], default: [])
    field(:language, :string)
    field(:meta, Fhir.v6().Meta)
    field(:modifierExtension, [Fhir.v6().Extension], default: [])
    field(:originalPrescription, Fhir.v6().Reference)
    field(:patient, Fhir.v6().Reference)
    field(:patientPaid, Fhir.v6().Money)
    field(:payee, Fhir.v6().ClaimPayee)
    field(:prescription, Fhir.v6().Reference)
    field(:priority, Fhir.v6().CodeableConcept)
    field(:procedure, [Fhir.v6().ClaimProcedure], default: [])
    field(:provider, Fhir.v6().Reference)
    field(:referral, Fhir.v6().Reference)
    field(:related, [Fhir.v6().ClaimRelated], default: [])
    field(:resourceType, :string, default: "Claim")
    field(:status, :string)
    field(:subType, Fhir.v6().CodeableConcept)
    field(:supportingInfo, [Fhir.v6().ClaimSupportingInfo], default: [])
    field(:text, Fhir.v6().Narrative)
    field(:total, Fhir.v6().Money)
    field(:traceNumber, [Fhir.v6().Identifier], default: [])
    field(:type, Fhir.v6().CodeableConcept)
    field(:use, :string)
  end
end
