defmodule Fhir.v6().ClaimResponseAddItem do
  use TypedStruct

  typedstruct do
    field(:_detailSequence, [Fhir.v6().Element], default: [])
    field(:_factor, Fhir.v6().Element)
    field(:_itemSequence, [Fhir.v6().Element], default: [])
    field(:_noteNumber, [Fhir.v6().Element], default: [])
    field(:_servicedDate, Fhir.v6().Element)
    field(:_subdetailSequence, [Fhir.v6().Element], default: [])
    field(:adjudication, [Fhir.v6().ClaimResponseAdjudication], default: [])
    field(:bodySite, [Fhir.v6().ClaimResponseBodySite], default: [])
    field(:detail, [Fhir.v6().ClaimResponseDetail1], default: [])
    field(:detailSequence, [:float], default: [])
    field(:extension, [Fhir.v6().Extension], default: [])
    field(:factor, :decimal)
    field(:id, :string)
    field(:itemSequence, [:float], default: [])
    field(:locationAddress, Fhir.v6().Address)
    field(:locationCodeableConcept, Fhir.v6().CodeableConcept)
    field(:locationReference, Fhir.v6().Reference)
    field(:modifier, [Fhir.v6().CodeableConcept], default: [])
    field(:modifierExtension, [Fhir.v6().Extension], default: [])
    field(:net, Fhir.v6().Money)
    field(:noteNumber, [:float], default: [])
    field(:productOrService, Fhir.v6().CodeableConcept)
    field(:productOrServiceEnd, Fhir.v6().CodeableConcept)
    field(:programCode, [Fhir.v6().CodeableConcept], default: [])
    field(:provider, [Fhir.v6().Reference], default: [])
    field(:quantity, Fhir.v6().Quantity)
    field(:request, [Fhir.v6().Reference], default: [])
    field(:revenue, Fhir.v6().CodeableConcept)
    field(:reviewOutcome, Fhir.v6().ClaimResponseReviewOutcome)
    field(:servicedDate, :string)
    field(:servicedPeriod, Fhir.v6().Period)
    field(:subdetailSequence, [:float], default: [])
    field(:tax, Fhir.v6().Money)
    field(:traceNumber, [Fhir.v6().Identifier], default: [])
    field(:unitPrice, Fhir.v6().Money)
  end
end
