defmodule Fhir.v6().ClinicalImpression do
  use TypedStruct

  typedstruct do
    field(:_date, Fhir.v6().Element)
    field(:_description, Fhir.v6().Element)
    field(:_effectiveDateTime, Fhir.v6().Element)
    field(:_implicitRules, Fhir.v6().Element)
    field(:_language, Fhir.v6().Element)
    field(:_protocol, [Fhir.v6().Element], default: [])
    field(:_status, Fhir.v6().Element)
    field(:_summary, Fhir.v6().Element)
    field(:changePattern, Fhir.v6().CodeableConcept)
    field(:contained, [Fhir.v6().ResourceList], default: [])
    field(:date, :datetime)
    field(:description, :string)
    field(:effectiveDateTime, :string)
    field(:effectivePeriod, Fhir.v6().Period)
    field(:encounter, Fhir.v6().Reference)
    field(:extension, [Fhir.v6().Extension], default: [])
    field(:finding, [Fhir.v6().ClinicalImpressionFinding], default: [])
    field(:id, :string)
    field(:identifier, [Fhir.v6().Identifier], default: [])
    field(:implicitRules, :string)
    field(:language, :string)
    field(:meta, Fhir.v6().Meta)
    field(:modifierExtension, [Fhir.v6().Extension], default: [])
    field(:note, [Fhir.v6().Annotation], default: [])
    field(:performer, Fhir.v6().Reference)
    field(:previous, Fhir.v6().Reference)
    field(:problem, [Fhir.v6().Reference], default: [])
    field(:prognosisCodeableConcept, [Fhir.v6().CodeableConcept], default: [])
    field(:prognosisReference, [Fhir.v6().Reference], default: [])
    field(:protocol, [:string], default: [])
    field(:resourceType, :string, default: "ClinicalImpression")
    field(:status, :string)
    field(:statusReason, Fhir.v6().CodeableConcept)
    field(:subject, Fhir.v6().Reference)
    field(:summary, :string)
    field(:supportingInfo, [Fhir.v6().Reference], default: [])
    field(:text, Fhir.v6().Narrative)
  end
end
