defmodule Fhir.v6().CodeSystem do
  use TypedStruct

  typedstruct do
    field(:_approvalDate, Fhir.v6().Element)
    field(:_caseSensitive, Fhir.v6().Element)
    field(:_compositional, Fhir.v6().Element)
    field(:_content, Fhir.v6().Element)
    field(:_copyright, Fhir.v6().Element)
    field(:_copyrightLabel, Fhir.v6().Element)
    field(:_count, Fhir.v6().Element)
    field(:_date, Fhir.v6().Element)
    field(:_description, Fhir.v6().Element)
    field(:_experimental, Fhir.v6().Element)
    field(:_hierarchyMeaning, Fhir.v6().Element)
    field(:_implicitRules, Fhir.v6().Element)
    field(:_language, Fhir.v6().Element)
    field(:_lastReviewDate, Fhir.v6().Element)
    field(:_name, Fhir.v6().Element)
    field(:_publisher, Fhir.v6().Element)
    field(:_purpose, Fhir.v6().Element)
    field(:_status, Fhir.v6().Element)
    field(:_title, Fhir.v6().Element)
    field(:_url, Fhir.v6().Element)
    field(:_version, Fhir.v6().Element)
    field(:_versionAlgorithmString, Fhir.v6().Element)
    field(:_versionNeeded, Fhir.v6().Element)
    field(:approvalDate, :date)
    field(:author, [Fhir.v6().ContactDetail], default: [])
    field(:caseSensitive, :boolean)
    field(:compositional, :boolean)
    field(:concept, [Fhir.v6().CodeSystemConcept], default: [])
    field(:contact, [Fhir.v6().ContactDetail], default: [])
    field(:contained, [Fhir.v6().ResourceList], default: [])
    field(:content, :string)
    field(:copyright, :string)
    field(:copyrightLabel, :string)
    field(:count, :float)
    field(:date, :datetime)
    field(:description, :string)
    field(:editor, [Fhir.v6().ContactDetail], default: [])
    field(:effectivePeriod, Fhir.v6().Period)
    field(:endorser, [Fhir.v6().ContactDetail], default: [])
    field(:experimental, :boolean)
    field(:extension, [Fhir.v6().Extension], default: [])
    field(:filter, [Fhir.v6().CodeSystemFilter], default: [])
    field(:hierarchyMeaning, :string)
    field(:id, :string)
    field(:identifier, [Fhir.v6().Identifier], default: [])
    field(:implicitRules, :string)
    field(:jurisdiction, [Fhir.v6().CodeableConcept], default: [])
    field(:language, :string)
    field(:lastReviewDate, :date)
    field(:meta, Fhir.v6().Meta)
    field(:modifierExtension, [Fhir.v6().Extension], default: [])
    field(:name, :string)
    field(:property, [Fhir.v6().CodeSystemProperty], default: [])
    field(:publisher, :string)
    field(:purpose, :string)
    field(:relatedArtifact, [Fhir.v6().RelatedArtifact], default: [])
    field(:resourceType, :string, default: "CodeSystem")
    field(:reviewer, [Fhir.v6().ContactDetail], default: [])
    field(:status, :string)
    field(:supplements, :string)
    field(:text, Fhir.v6().Narrative)
    field(:title, :string)
    field(:topic, [Fhir.v6().CodeableConcept], default: [])
    field(:url, :string)
    field(:useContext, [Fhir.v6().UsageContext], default: [])
    field(:valueSet, :string)
    field(:version, :string)
    field(:versionAlgorithmCoding, Fhir.v6().Coding)
    field(:versionAlgorithmString, :string)
    field(:versionNeeded, :boolean)
  end
end
