defmodule Fhir.v6().CommunicationRequest do
  use TypedStruct

  typedstruct do
    field(:_authoredOn, Fhir.v6().Element)
    field(:_doNotPerform, Fhir.v6().Element)
    field(:_implicitRules, Fhir.v6().Element)
    field(:_intent, Fhir.v6().Element)
    field(:_language, Fhir.v6().Element)
    field(:_occurrenceDateTime, Fhir.v6().Element)
    field(:_priority, Fhir.v6().Element)
    field(:_status, Fhir.v6().Element)
    field(:about, [Fhir.v6().Reference], default: [])
    field(:authoredOn, :datetime)
    field(:basedOn, [Fhir.v6().Reference], default: [])
    field(:category, [Fhir.v6().CodeableConcept], default: [])
    field(:contained, [Fhir.v6().ResourceList], default: [])
    field(:doNotPerform, :boolean)
    field(:encounter, Fhir.v6().Reference)
    field(:extension, [Fhir.v6().Extension], default: [])
    field(:groupIdentifier, Fhir.v6().Identifier)
    field(:id, :string)
    field(:identifier, [Fhir.v6().Identifier], default: [])
    field(:implicitRules, :string)
    field(:informationProvider, [Fhir.v6().Reference], default: [])
    field(:intent, :string)
    field(:language, :string)
    field(:medium, [Fhir.v6().CodeableConcept], default: [])
    field(:meta, Fhir.v6().Meta)
    field(:modifierExtension, [Fhir.v6().Extension], default: [])
    field(:note, [Fhir.v6().Annotation], default: [])
    field(:occurrenceDateTime, :string)
    field(:occurrencePeriod, Fhir.v6().Period)
    field(:payload, [Fhir.v6().CommunicationRequestPayload], default: [])
    field(:priority, :string)
    field(:reason, [Fhir.v6().CodeableReference], default: [])
    field(:recipient, [Fhir.v6().Reference], default: [])
    field(:replaces, [Fhir.v6().Reference], default: [])
    field(:requester, Fhir.v6().Reference)
    field(:resourceType, :string, default: "CommunicationRequest")
    field(:status, :string)
    field(:statusReason, Fhir.v6().CodeableConcept)
    field(:subject, Fhir.v6().Reference)
    field(:text, Fhir.v6().Narrative)
  end
end
