defmodule Fhir.v6().Communication do
  use TypedStruct

  typedstruct do
    field(:_implicitRules, Fhir.v6().Element)
    field(:_instantiatesUri, [Fhir.v6().Element], default: [])
    field(:_language, Fhir.v6().Element)
    field(:_priority, Fhir.v6().Element)
    field(:_received, Fhir.v6().Element)
    field(:_sent, Fhir.v6().Element)
    field(:_status, Fhir.v6().Element)
    field(:about, [Fhir.v6().Reference], default: [])
    field(:basedOn, [Fhir.v6().Reference], default: [])
    field(:category, [Fhir.v6().CodeableConcept], default: [])
    field(:contained, [Fhir.v6().ResourceList], default: [])
    field(:encounter, Fhir.v6().Reference)
    field(:extension, [Fhir.v6().Extension], default: [])
    field(:id, :string)
    field(:identifier, [Fhir.v6().Identifier], default: [])
    field(:implicitRules, :string)
    field(:inResponseTo, [Fhir.v6().Reference], default: [])
    field(:instantiatesCanonical, [:string], default: [])
    field(:instantiatesUri, [:string], default: [])
    field(:language, :string)
    field(:medium, [Fhir.v6().CodeableConcept], default: [])
    field(:meta, Fhir.v6().Meta)
    field(:modifierExtension, [Fhir.v6().Extension], default: [])
    field(:note, [Fhir.v6().Annotation], default: [])
    field(:partOf, [Fhir.v6().Reference], default: [])
    field(:payload, [Fhir.v6().CommunicationPayload], default: [])
    field(:priority, :string)
    field(:reason, [Fhir.v6().CodeableReference], default: [])
    field(:received, :datetime)
    field(:recipient, [Fhir.v6().Reference], default: [])
    field(:resourceType, :string, default: "Communication")
    field(:sender, Fhir.v6().Reference)
    field(:sent, :datetime)
    field(:status, :string)
    field(:statusReason, Fhir.v6().CodeableConcept)
    field(:subject, Fhir.v6().Reference)
    field(:text, Fhir.v6().Narrative)
    field(:topic, Fhir.v6().CodeableConcept)
  end
end
