defmodule Fhir.v6().Composition do
  use TypedStruct

  typedstruct do
    field(:_date, Fhir.v6().Element)
    field(:_implicitRules, Fhir.v6().Element)
    field(:_language, Fhir.v6().Element)
    field(:_name, Fhir.v6().Element)
    field(:_status, Fhir.v6().Element)
    field(:_title, Fhir.v6().Element)
    field(:_url, Fhir.v6().Element)
    field(:_version, Fhir.v6().Element)
    field(:attester, [Fhir.v6().CompositionAttester], default: [])
    field(:author, [Fhir.v6().Reference], default: [])
    field(:category, [Fhir.v6().CodeableConcept], default: [])
    field(:contained, [Fhir.v6().ResourceList], default: [])
    field(:custodian, Fhir.v6().Reference)
    field(:date, :datetime)
    field(:encounter, Fhir.v6().Reference)
    field(:event, [Fhir.v6().CompositionEvent], default: [])
    field(:extension, [Fhir.v6().Extension], default: [])
    field(:id, :string)
    field(:identifier, [Fhir.v6().Identifier], default: [])
    field(:implicitRules, :string)
    field(:language, :string)
    field(:meta, Fhir.v6().Meta)
    field(:modifierExtension, [Fhir.v6().Extension], default: [])
    field(:name, :string)
    field(:note, [Fhir.v6().Annotation], default: [])
    field(:relatesTo, [Fhir.v6().RelatedArtifact], default: [])
    field(:resourceType, :string, default: "Composition")
    field(:section, [Fhir.v6().CompositionSection], default: [])
    field(:status, :string)
    field(:subject, [Fhir.v6().Reference], default: [])
    field(:text, Fhir.v6().Narrative)
    field(:title, :string)
    field(:type, Fhir.v6().CodeableConcept)
    field(:url, :string)
    field(:useContext, [Fhir.v6().UsageContext], default: [])
    field(:version, :string)
  end
end
