defmodule Fhir.v6().Condition do
  use TypedStruct

  typedstruct do
    field(:_abatementDateTime, Fhir.v6().Element)
    field(:_abatementString, Fhir.v6().Element)
    field(:_implicitRules, Fhir.v6().Element)
    field(:_language, Fhir.v6().Element)
    field(:_onsetDateTime, Fhir.v6().Element)
    field(:_onsetString, Fhir.v6().Element)
    field(:_recordedDate, Fhir.v6().Element)
    field(:abatementAge, Fhir.v6().Age)
    field(:abatementDateTime, :string)
    field(:abatementPeriod, Fhir.v6().Period)
    field(:abatementRange, Fhir.v6().Range)
    field(:abatementString, :string)
    field(:bodySite, [Fhir.v6().CodeableConcept], default: [])
    field(:category, [Fhir.v6().CodeableConcept], default: [])
    field(:clinicalStatus, Fhir.v6().CodeableConcept)
    field(:code, Fhir.v6().CodeableConcept)
    field(:contained, [Fhir.v6().ResourceList], default: [])
    field(:encounter, Fhir.v6().Reference)
    field(:evidence, [Fhir.v6().CodeableReference], default: [])
    field(:extension, [Fhir.v6().Extension], default: [])
    field(:id, :string)
    field(:identifier, [Fhir.v6().Identifier], default: [])
    field(:implicitRules, :string)
    field(:language, :string)
    field(:meta, Fhir.v6().Meta)
    field(:modifierExtension, [Fhir.v6().Extension], default: [])
    field(:note, [Fhir.v6().Annotation], default: [])
    field(:onsetAge, Fhir.v6().Age)
    field(:onsetDateTime, :string)
    field(:onsetPeriod, Fhir.v6().Period)
    field(:onsetRange, Fhir.v6().Range)
    field(:onsetString, :string)
    field(:participant, [Fhir.v6().ConditionParticipant], default: [])
    field(:recordedDate, :datetime)
    field(:resourceType, :string, default: "Condition")
    field(:severity, Fhir.v6().CodeableConcept)
    field(:stage, [Fhir.v6().ConditionStage], default: [])
    field(:subject, Fhir.v6().Reference)
    field(:text, Fhir.v6().Narrative)
    field(:verificationStatus, Fhir.v6().CodeableConcept)
  end
end
