defmodule Fhir.v6().ConditionDefinition do
  use TypedStruct

  typedstruct do
    field(:_approvalDate, Fhir.v6().Element)
    field(:_copyright, Fhir.v6().Element)
    field(:_copyrightLabel, Fhir.v6().Element)
    field(:_date, Fhir.v6().Element)
    field(:_definition, [Fhir.v6().Element], default: [])
    field(:_description, Fhir.v6().Element)
    field(:_experimental, Fhir.v6().Element)
    field(:_hasBodySite, Fhir.v6().Element)
    field(:_hasSeverity, Fhir.v6().Element)
    field(:_hasStage, Fhir.v6().Element)
    field(:_implicitRules, Fhir.v6().Element)
    field(:_language, Fhir.v6().Element)
    field(:_lastReviewDate, Fhir.v6().Element)
    field(:_name, Fhir.v6().Element)
    field(:_publisher, Fhir.v6().Element)
    field(:_purpose, Fhir.v6().Element)
    field(:_status, Fhir.v6().Element)
    field(:_subtitle, Fhir.v6().Element)
    field(:_title, Fhir.v6().Element)
    field(:_url, Fhir.v6().Element)
    field(:_version, Fhir.v6().Element)
    field(:_versionAlgorithmString, Fhir.v6().Element)
    field(:approvalDate, :date)
    field(:author, [Fhir.v6().ContactDetail], default: [])
    field(:bodySite, Fhir.v6().CodeableConcept)
    field(:code, Fhir.v6().CodeableConcept)
    field(:contact, [Fhir.v6().ContactDetail], default: [])
    field(:contained, [Fhir.v6().ResourceList], default: [])
    field(:copyright, :string)
    field(:copyrightLabel, :string)
    field(:date, :datetime)
    field(:definition, [:string], default: [])
    field(:description, :string)
    field(:editor, [Fhir.v6().ContactDetail], default: [])
    field(:effectivePeriod, Fhir.v6().Period)
    field(:endorser, [Fhir.v6().ContactDetail], default: [])
    field(:experimental, :boolean)
    field(:extension, [Fhir.v6().Extension], default: [])
    field(:hasBodySite, :boolean)
    field(:hasSeverity, :boolean)
    field(:hasStage, :boolean)
    field(:id, :string)
    field(:identifier, [Fhir.v6().Identifier], default: [])
    field(:implicitRules, :string)
    field(:jurisdiction, [Fhir.v6().CodeableConcept], default: [])
    field(:language, :string)
    field(:lastReviewDate, :date)
    field(:medication, [Fhir.v6().ConditionDefinitionMedication], default: [])
    field(:meta, Fhir.v6().Meta)
    field(:modifierExtension, [Fhir.v6().Extension], default: [])
    field(:name, :string)
    field(:observation, [Fhir.v6().ConditionDefinitionObservation], default: [])
    field(:plan, [Fhir.v6().ConditionDefinitionPlan], default: [])
    field(:precondition, [Fhir.v6().ConditionDefinitionPrecondition], default: [])
    field(:publisher, :string)
    field(:purpose, :string)
    field(:questionnaire, [Fhir.v6().ConditionDefinitionQuestionnaire], default: [])
    field(:relatedArtifact, [Fhir.v6().RelatedArtifact], default: [])
    field(:resourceType, :string, default: "ConditionDefinition")
    field(:reviewer, [Fhir.v6().ContactDetail], default: [])
    field(:severity, Fhir.v6().CodeableConcept)
    field(:stage, Fhir.v6().CodeableConcept)
    field(:status, :string)
    field(:subtitle, :string)
    field(:team, [Fhir.v6().Reference], default: [])
    field(:text, Fhir.v6().Narrative)
    field(:title, :string)
    field(:topic, [Fhir.v6().CodeableConcept], default: [])
    field(:url, :string)
    field(:useContext, [Fhir.v6().UsageContext], default: [])
    field(:version, :string)
    field(:versionAlgorithmCoding, Fhir.v6().Coding)
    field(:versionAlgorithmString, :string)
  end
end
