defmodule Fhir.v6().Consent do
  use TypedStruct

  typedstruct do
    field(:_date, Fhir.v6().Element)
    field(:_decision, Fhir.v6().Element)
    field(:_implicitRules, Fhir.v6().Element)
    field(:_language, Fhir.v6().Element)
    field(:_status, Fhir.v6().Element)
    field(:category, [Fhir.v6().CodeableConcept], default: [])
    field(:contained, [Fhir.v6().ResourceList], default: [])
    field(:controller, [Fhir.v6().Reference], default: [])
    field(:date, :date)
    field(:decision, :string)
    field(:extension, [Fhir.v6().Extension], default: [])
    field(:grantee, [Fhir.v6().Reference], default: [])
    field(:grantor, [Fhir.v6().Reference], default: [])
    field(:id, :string)
    field(:identifier, [Fhir.v6().Identifier], default: [])
    field(:implicitRules, :string)
    field(:language, :string)
    field(:manager, [Fhir.v6().Reference], default: [])
    field(:meta, Fhir.v6().Meta)
    field(:modifierExtension, [Fhir.v6().Extension], default: [])
    field(:period, Fhir.v6().Period)
    field(:policyBasis, Fhir.v6().ConsentPolicyBasis)
    field(:policyText, [Fhir.v6().Reference], default: [])
    field(:provision, [Fhir.v6().ConsentProvision], default: [])
    field(:regulatoryBasis, [Fhir.v6().CodeableConcept], default: [])
    field(:resourceType, :string, default: "Consent")
    field(:sourceAttachment, [Fhir.v6().Attachment], default: [])
    field(:sourceReference, [Fhir.v6().Reference], default: [])
    field(:status, :string)
    field(:subject, Fhir.v6().Reference)
    field(:text, Fhir.v6().Narrative)
    field(:verification, [Fhir.v6().ConsentVerification], default: [])
  end
end
