defmodule Fhir.v6().Contract do
  use TypedStruct

  typedstruct do
    field(:_alias, [Fhir.v6().Element], default: [])
    field(:_implicitRules, Fhir.v6().Element)
    field(:_instantiatesUri, Fhir.v6().Element)
    field(:_issued, Fhir.v6().Element)
    field(:_language, Fhir.v6().Element)
    field(:_name, Fhir.v6().Element)
    field(:_status, Fhir.v6().Element)
    field(:_subtitle, Fhir.v6().Element)
    field(:_title, Fhir.v6().Element)
    field(:_url, Fhir.v6().Element)
    field(:_version, Fhir.v6().Element)
    field(:alias, [:string], default: [])
    field(:applies, Fhir.v6().Period)
    field(:author, Fhir.v6().Reference)
    field(:authority, [Fhir.v6().Reference], default: [])
    field(:contained, [Fhir.v6().ResourceList], default: [])
    field(:contentDefinition, Fhir.v6().ContractContentDefinition)
    field(:contentDerivative, Fhir.v6().CodeableConcept)
    field(:domain, [Fhir.v6().Reference], default: [])
    field(:expirationType, Fhir.v6().CodeableConcept)
    field(:extension, [Fhir.v6().Extension], default: [])
    field(:friendly, [Fhir.v6().ContractFriendly], default: [])
    field(:id, :string)
    field(:identifier, [Fhir.v6().Identifier], default: [])
    field(:implicitRules, :string)
    field(:instantiatesCanonical, Fhir.v6().Reference)
    field(:instantiatesUri, :string)
    field(:issued, :datetime)
    field(:language, :string)
    field(:legal, [Fhir.v6().ContractLegal], default: [])
    field(:legalState, Fhir.v6().CodeableConcept)
    field(:legallyBindingAttachment, Fhir.v6().Attachment)
    field(:legallyBindingReference, Fhir.v6().Reference)
    field(:meta, Fhir.v6().Meta)
    field(:modifierExtension, [Fhir.v6().Extension], default: [])
    field(:name, :string)
    field(:relevantHistory, [Fhir.v6().Reference], default: [])
    field(:resourceType, :string, default: "Contract")
    field(:rule, [Fhir.v6().ContractRule], default: [])
    field(:scope, Fhir.v6().CodeableConcept)
    field(:signer, [Fhir.v6().ContractSigner], default: [])
    field(:site, [Fhir.v6().Reference], default: [])
    field(:status, :string)
    field(:subType, [Fhir.v6().CodeableConcept], default: [])
    field(:subject, [Fhir.v6().Reference], default: [])
    field(:subtitle, :string)
    field(:supportingInfo, [Fhir.v6().Reference], default: [])
    field(:term, [Fhir.v6().ContractTerm], default: [])
    field(:text, Fhir.v6().Narrative)
    field(:title, :string)
    field(:topicCodeableConcept, Fhir.v6().CodeableConcept)
    field(:topicReference, Fhir.v6().Reference)
    field(:type, Fhir.v6().CodeableConcept)
    field(:url, :string)
    field(:version, :string)
  end
end
