defmodule Fhir.v6().Coverage do
  use TypedStruct

  typedstruct do
    field(:_dependent, Fhir.v6().Element)
    field(:_implicitRules, Fhir.v6().Element)
    field(:_kind, Fhir.v6().Element)
    field(:_language, Fhir.v6().Element)
    field(:_network, Fhir.v6().Element)
    field(:_order, Fhir.v6().Element)
    field(:_status, Fhir.v6().Element)
    field(:_subrogation, Fhir.v6().Element)
    field(:beneficiary, Fhir.v6().Reference)
    field(:class, [Fhir.v6().CoverageClass], default: [])
    field(:contained, [Fhir.v6().ResourceList], default: [])
    field(:contract, [Fhir.v6().Reference], default: [])
    field(:costToBeneficiary, [Fhir.v6().CoverageCostToBeneficiary], default: [])
    field(:dependent, :string)
    field(:extension, [Fhir.v6().Extension], default: [])
    field(:id, :string)
    field(:identifier, [Fhir.v6().Identifier], default: [])
    field(:implicitRules, :string)
    field(:insurancePlan, Fhir.v6().Reference)
    field(:insurer, Fhir.v6().Reference)
    field(:kind, :string)
    field(:language, :string)
    field(:meta, Fhir.v6().Meta)
    field(:modifierExtension, [Fhir.v6().Extension], default: [])
    field(:network, :string)
    field(:order, :float)
    field(:paymentBy, [Fhir.v6().CoveragePaymentBy], default: [])
    field(:period, Fhir.v6().Period)
    field(:policyHolder, Fhir.v6().Reference)
    field(:relationship, Fhir.v6().CodeableConcept)
    field(:resourceType, :string, default: "Coverage")
    field(:status, :string)
    field(:subrogation, :boolean)
    field(:subscriber, Fhir.v6().Reference)
    field(:subscriberId, [Fhir.v6().Identifier], default: [])
    field(:text, Fhir.v6().Narrative)
    field(:type, Fhir.v6().CodeableConcept)
  end
end
