defmodule Fhir.v6().CoverageEligibilityResponse do
  use TypedStruct

  typedstruct do
    field(:_created, Fhir.v6().Element)
    field(:_disposition, Fhir.v6().Element)
    field(:_implicitRules, Fhir.v6().Element)
    field(:_language, Fhir.v6().Element)
    field(:_outcome, Fhir.v6().Element)
    field(:_preAuthRef, Fhir.v6().Element)
    field(:_purpose, [Fhir.v6().Element], default: [])
    field(:_servicedDate, Fhir.v6().Element)
    field(:_status, Fhir.v6().Element)
    field(:contained, [Fhir.v6().ResourceList], default: [])
    field(:created, :datetime)
    field(:disposition, :string)
    field(:error, [Fhir.v6().CoverageEligibilityResponseError], default: [])
    field(:event, [Fhir.v6().CoverageEligibilityResponseEvent], default: [])
    field(:extension, [Fhir.v6().Extension], default: [])
    field(:form, Fhir.v6().CodeableConcept)
    field(:id, :string)
    field(:identifier, [Fhir.v6().Identifier], default: [])
    field(:implicitRules, :string)
    field(:insurance, [Fhir.v6().CoverageEligibilityResponseInsurance], default: [])
    field(:insurer, Fhir.v6().Reference)
    field(:language, :string)
    field(:meta, Fhir.v6().Meta)
    field(:modifierExtension, [Fhir.v6().Extension], default: [])
    field(:outcome, :string)
    field(:patient, Fhir.v6().Reference)
    field(:preAuthRef, :string)
    field(:purpose, [:string], default: [])
    field(:request, Fhir.v6().Reference)
    field(:requestor, Fhir.v6().Reference)
    field(:resourceType, :string, default: "CoverageEligibilityResponse")
    field(:servicedDate, :string)
    field(:servicedPeriod, Fhir.v6().Period)
    field(:status, :string)
    field(:text, Fhir.v6().Narrative)
  end
end
