defmodule Fhir.v6().Device do
  use TypedStruct

  typedstruct do
    field(:_displayName, Fhir.v6().Element)
    field(:_expirationDate, Fhir.v6().Element)
    field(:_implicitRules, Fhir.v6().Element)
    field(:_language, Fhir.v6().Element)
    field(:_lotNumber, Fhir.v6().Element)
    field(:_manufactureDate, Fhir.v6().Element)
    field(:_manufacturer, Fhir.v6().Element)
    field(:_modelNumber, Fhir.v6().Element)
    field(:_partNumber, Fhir.v6().Element)
    field(:_serialNumber, Fhir.v6().Element)
    field(:_status, Fhir.v6().Element)
    field(:_url, Fhir.v6().Element)
    field(:availabilityStatus, Fhir.v6().CodeableConcept)
    field(:biologicalSourceEvent, Fhir.v6().Identifier)
    field(:category, [Fhir.v6().CodeableConcept], default: [])
    field(:conformsTo, [Fhir.v6().DeviceConformsTo], default: [])
    field(:contact, [Fhir.v6().ContactPoint], default: [])
    field(:contained, [Fhir.v6().ResourceList], default: [])
    field(:cycle, Fhir.v6().Count)
    field(:definition, Fhir.v6().CodeableReference)
    field(:displayName, :string)
    field(:duration, Fhir.v6().Duration)
    field(:endpoint, [Fhir.v6().Reference], default: [])
    field(:expirationDate, :datetime)
    field(:extension, [Fhir.v6().Extension], default: [])
    field(:gateway, [Fhir.v6().CodeableReference], default: [])
    field(:id, :string)
    field(:identifier, [Fhir.v6().Identifier], default: [])
    field(:implicitRules, :string)
    field(:language, :string)
    field(:location, Fhir.v6().Reference)
    field(:lotNumber, :string)
    field(:manufactureDate, :datetime)
    field(:manufacturer, :string)
    field(:meta, Fhir.v6().Meta)
    field(:mode, Fhir.v6().CodeableConcept)
    field(:modelNumber, :string)
    field(:modifierExtension, [Fhir.v6().Extension], default: [])
    field(:name, [Fhir.v6().DeviceName], default: [])
    field(:note, [Fhir.v6().Annotation], default: [])
    field(:owner, Fhir.v6().Reference)
    field(:parent, Fhir.v6().Reference)
    field(:partNumber, :string)
    field(:property, [Fhir.v6().DeviceProperty], default: [])
    field(:resourceType, :string, default: "Device")
    field(:safety, [Fhir.v6().CodeableConcept], default: [])
    field(:serialNumber, :string)
    field(:status, :string)
    field(:text, Fhir.v6().Narrative)
    field(:type, [Fhir.v6().CodeableConcept], default: [])
    field(:udiCarrier, [Fhir.v6().DeviceUdiCarrier], default: [])
    field(:url, :string)
    field(:version, [Fhir.v6().DeviceVersion], default: [])
  end
end
