defmodule Fhir.v6().DeviceRequest do
  use TypedStruct

  typedstruct do
    field(:_asNeeded, Fhir.v6().Element)
    field(:_authoredOn, Fhir.v6().Element)
    field(:_doNotPerform, Fhir.v6().Element)
    field(:_implicitRules, Fhir.v6().Element)
    field(:_instantiatesUri, [Fhir.v6().Element], default: [])
    field(:_intent, Fhir.v6().Element)
    field(:_language, Fhir.v6().Element)
    field(:_occurrenceDateTime, Fhir.v6().Element)
    field(:_priority, Fhir.v6().Element)
    field(:_quantity, Fhir.v6().Element)
    field(:_status, Fhir.v6().Element)
    field(:asNeeded, :boolean)
    field(:asNeededFor, Fhir.v6().CodeableConcept)
    field(:authoredOn, :datetime)
    field(:basedOn, [Fhir.v6().Reference], default: [])
    field(:code, Fhir.v6().CodeableReference)
    field(:contained, [Fhir.v6().ResourceList], default: [])
    field(:doNotPerform, :boolean)
    field(:encounter, Fhir.v6().Reference)
    field(:extension, [Fhir.v6().Extension], default: [])
    field(:groupIdentifier, Fhir.v6().Identifier)
    field(:id, :string)
    field(:identifier, [Fhir.v6().Identifier], default: [])
    field(:implicitRules, :string)
    field(:instantiatesCanonical, [:string], default: [])
    field(:instantiatesUri, [:string], default: [])
    field(:insurance, [Fhir.v6().Reference], default: [])
    field(:intent, :string)
    field(:language, :string)
    field(:meta, Fhir.v6().Meta)
    field(:modifierExtension, [Fhir.v6().Extension], default: [])
    field(:note, [Fhir.v6().Annotation], default: [])
    field(:occurrenceDateTime, :string)
    field(:occurrencePeriod, Fhir.v6().Period)
    field(:occurrenceTiming, Fhir.v6().Timing)
    field(:parameter, [Fhir.v6().DeviceRequestParameter], default: [])
    field(:performer, Fhir.v6().CodeableReference)
    field(:priority, :string)
    field(:quantity, :float)
    field(:reason, [Fhir.v6().CodeableReference], default: [])
    field(:relevantHistory, [Fhir.v6().Reference], default: [])
    field(:replaces, [Fhir.v6().Reference], default: [])
    field(:requester, Fhir.v6().Reference)
    field(:resourceType, :string, default: "DeviceRequest")
    field(:status, :string)
    field(:subject, Fhir.v6().Reference)
    field(:supportingInfo, [Fhir.v6().Reference], default: [])
    field(:text, Fhir.v6().Narrative)
  end
end
