defmodule Fhir.v6().DeviceDispense do
  use TypedStruct

  typedstruct do
    field(:_implicitRules, Fhir.v6().Element)
    field(:_language, Fhir.v6().Element)
    field(:_preparedDate, Fhir.v6().Element)
    field(:_status, Fhir.v6().Element)
    field(:_usageInstruction, Fhir.v6().Element)
    field(:_whenHandedOver, Fhir.v6().Element)
    field(:basedOn, [Fhir.v6().Reference], default: [])
    field(:category, [Fhir.v6().CodeableConcept], default: [])
    field(:contained, [Fhir.v6().ResourceList], default: [])
    field(:destination, Fhir.v6().Reference)
    field(:device, Fhir.v6().CodeableReference)
    field(:encounter, Fhir.v6().Reference)
    field(:eventHistory, [Fhir.v6().Reference], default: [])
    field(:extension, [Fhir.v6().Extension], default: [])
    field(:id, :string)
    field(:identifier, [Fhir.v6().Identifier], default: [])
    field(:implicitRules, :string)
    field(:language, :string)
    field(:location, Fhir.v6().Reference)
    field(:meta, Fhir.v6().Meta)
    field(:modifierExtension, [Fhir.v6().Extension], default: [])
    field(:note, [Fhir.v6().Annotation], default: [])
    field(:partOf, [Fhir.v6().Reference], default: [])
    field(:performer, [Fhir.v6().DeviceDispensePerformer], default: [])
    field(:preparedDate, :datetime)
    field(:quantity, Fhir.v6().Quantity)
    field(:receiver, Fhir.v6().Reference)
    field(:resourceType, :string, default: "DeviceDispense")
    field(:status, :string)
    field(:statusReason, Fhir.v6().CodeableReference)
    field(:subject, Fhir.v6().Reference)
    field(:supportingInformation, [Fhir.v6().Reference], default: [])
    field(:text, Fhir.v6().Narrative)
    field(:type, Fhir.v6().CodeableConcept)
    field(:usageInstruction, :string)
    field(:whenHandedOver, :datetime)
  end
end
