defmodule Fhir.v6().DeviceDefinition do
  use TypedStruct

  typedstruct do
    field(:_description, Fhir.v6().Element)
    field(:_implicitRules, Fhir.v6().Element)
    field(:_language, Fhir.v6().Element)
    field(:_modelNumber, Fhir.v6().Element)
    field(:_partNumber, Fhir.v6().Element)
    field(:_productionIdentifierInUDI, [Fhir.v6().Element], default: [])
    field(:chargeItem, [Fhir.v6().DeviceDefinitionChargeItem], default: [])
    field(:classification, [Fhir.v6().DeviceDefinitionClassification], default: [])
    field(:conformsTo, [Fhir.v6().DeviceDefinitionConformsTo], default: [])
    field(:contact, [Fhir.v6().ContactPoint], default: [])
    field(:contained, [Fhir.v6().ResourceList], default: [])
    field(:correctiveAction, Fhir.v6().DeviceDefinitionCorrectiveAction)
    field(:description, :string)
    field(:deviceName, [Fhir.v6().DeviceDefinitionDeviceName], default: [])
    field(:extension, [Fhir.v6().Extension], default: [])
    field(:guideline, Fhir.v6().DeviceDefinitionGuideline)
    field(:hasPart, [Fhir.v6().DeviceDefinitionHasPart], default: [])
    field(:id, :string)
    field(:identifier, [Fhir.v6().Identifier], default: [])
    field(:implicitRules, :string)
    field(:language, :string)
    field(:languageCode, [Fhir.v6().CodeableConcept], default: [])
    field(:link, [Fhir.v6().DeviceDefinitionLink], default: [])
    field(:manufacturer, Fhir.v6().Reference)
    field(:material, [Fhir.v6().DeviceDefinitionMaterial], default: [])
    field(:meta, Fhir.v6().Meta)
    field(:modelNumber, :string)
    field(:modifierExtension, [Fhir.v6().Extension], default: [])
    field(:note, [Fhir.v6().Annotation], default: [])
    field(:owner, Fhir.v6().Reference)
    field(:packaging, [Fhir.v6().DeviceDefinitionPackaging], default: [])
    field(:partNumber, :string)
    field(:productionIdentifierInUDI, [:string], default: [])
    field(:property, [Fhir.v6().DeviceDefinitionProperty], default: [])
    field(:regulatoryIdentifier, [Fhir.v6().DeviceDefinitionRegulatoryIdentifier], default: [])
    field(:resourceType, :string, default: "DeviceDefinition")
    field(:safety, [Fhir.v6().CodeableConcept], default: [])
    field(:shelfLifeStorage, [Fhir.v6().ProductShelfLife], default: [])
    field(:text, Fhir.v6().Narrative)
    field(:udiDeviceIdentifier, [Fhir.v6().DeviceDefinitionUdiDeviceIdentifier], default: [])
    field(:version, [Fhir.v6().DeviceDefinitionVersion], default: [])
  end
end
