defmodule Fhir.v6().DeviceUsage do
  use TypedStruct

  typedstruct do
    field(:_dateAsserted, Fhir.v6().Element)
    field(:_implicitRules, Fhir.v6().Element)
    field(:_language, Fhir.v6().Element)
    field(:_status, Fhir.v6().Element)
    field(:_timingDateTime, Fhir.v6().Element)
    field(:adherence, Fhir.v6().DeviceUsageAdherence)
    field(:basedOn, [Fhir.v6().Reference], default: [])
    field(:bodySite, Fhir.v6().CodeableReference)
    field(:category, [Fhir.v6().CodeableConcept], default: [])
    field(:contained, [Fhir.v6().ResourceList], default: [])
    field(:context, Fhir.v6().Reference)
    field(:dateAsserted, :datetime)
    field(:derivedFrom, [Fhir.v6().Reference], default: [])
    field(:device, Fhir.v6().CodeableReference)
    field(:extension, [Fhir.v6().Extension], default: [])
    field(:id, :string)
    field(:identifier, [Fhir.v6().Identifier], default: [])
    field(:implicitRules, :string)
    field(:informationSource, Fhir.v6().Reference)
    field(:language, :string)
    field(:meta, Fhir.v6().Meta)
    field(:modifierExtension, [Fhir.v6().Extension], default: [])
    field(:note, [Fhir.v6().Annotation], default: [])
    field(:patient, Fhir.v6().Reference)
    field(:reason, [Fhir.v6().CodeableReference], default: [])
    field(:resourceType, :string, default: "DeviceUsage")
    field(:status, :string)
    field(:text, Fhir.v6().Narrative)
    field(:timingDateTime, :string)
    field(:timingPeriod, Fhir.v6().Period)
    field(:timingTiming, Fhir.v6().Timing)
    field(:usageReason, [Fhir.v6().CodeableConcept], default: [])
    field(:usageStatus, Fhir.v6().CodeableConcept)
  end
end
