defmodule Fhir.v6().DiagnosticReport do
  use TypedStruct

  typedstruct do
    field(:_conclusion, Fhir.v6().Element)
    field(:_effectiveDateTime, Fhir.v6().Element)
    field(:_implicitRules, Fhir.v6().Element)
    field(:_issued, Fhir.v6().Element)
    field(:_language, Fhir.v6().Element)
    field(:_status, Fhir.v6().Element)
    field(:basedOn, [Fhir.v6().Reference], default: [])
    field(:category, [Fhir.v6().CodeableConcept], default: [])
    field(:code, Fhir.v6().CodeableConcept)
    field(:composition, Fhir.v6().Reference)
    field(:conclusion, :string)
    field(:conclusionCode, [Fhir.v6().CodeableConcept], default: [])
    field(:contained, [Fhir.v6().ResourceList], default: [])
    field(:effectiveDateTime, :string)
    field(:effectivePeriod, Fhir.v6().Period)
    field(:encounter, Fhir.v6().Reference)
    field(:extension, [Fhir.v6().Extension], default: [])
    field(:id, :string)
    field(:identifier, [Fhir.v6().Identifier], default: [])
    field(:implicitRules, :string)
    field(:issued, :timestamp)
    field(:language, :string)
    field(:media, [Fhir.v6().DiagnosticReportMedia], default: [])
    field(:meta, Fhir.v6().Meta)
    field(:modifierExtension, [Fhir.v6().Extension], default: [])
    field(:note, [Fhir.v6().Annotation], default: [])
    field(:performer, [Fhir.v6().Reference], default: [])
    field(:presentedForm, [Fhir.v6().Attachment], default: [])
    field(:resourceType, :string, default: "DiagnosticReport")
    field(:result, [Fhir.v6().Reference], default: [])
    field(:resultsInterpreter, [Fhir.v6().Reference], default: [])
    field(:specimen, [Fhir.v6().Reference], default: [])
    field(:status, :string)
    field(:study, [Fhir.v6().Reference], default: [])
    field(:subject, Fhir.v6().Reference)
    field(:supportingInfo, [Fhir.v6().DiagnosticReportSupportingInfo], default: [])
    field(:text, Fhir.v6().Narrative)
  end
end
