defmodule Fhir.v6().Encounter do
  use TypedStruct

  typedstruct do
    field(:_implicitRules, Fhir.v6().Element)
    field(:_language, Fhir.v6().Element)
    field(:_plannedEndDate, Fhir.v6().Element)
    field(:_plannedStartDate, Fhir.v6().Element)
    field(:_status, Fhir.v6().Element)
    field(:account, [Fhir.v6().Reference], default: [])
    field(:actualPeriod, Fhir.v6().Period)
    field(:admission, Fhir.v6().EncounterAdmission)
    field(:appointment, [Fhir.v6().Reference], default: [])
    field(:basedOn, [Fhir.v6().Reference], default: [])
    field(:careTeam, [Fhir.v6().Reference], default: [])
    field(:class, [Fhir.v6().CodeableConcept], default: [])
    field(:contained, [Fhir.v6().ResourceList], default: [])
    field(:diagnosis, [Fhir.v6().EncounterDiagnosis], default: [])
    field(:dietPreference, [Fhir.v6().CodeableConcept], default: [])
    field(:episodeOfCare, [Fhir.v6().Reference], default: [])
    field(:extension, [Fhir.v6().Extension], default: [])
    field(:id, :string)
    field(:identifier, [Fhir.v6().Identifier], default: [])
    field(:implicitRules, :string)
    field(:language, :string)
    field(:length, Fhir.v6().Duration)
    field(:location, [Fhir.v6().EncounterLocation], default: [])
    field(:meta, Fhir.v6().Meta)
    field(:modifierExtension, [Fhir.v6().Extension], default: [])
    field(:partOf, Fhir.v6().Reference)
    field(:participant, [Fhir.v6().EncounterParticipant], default: [])
    field(:plannedEndDate, :datetime)
    field(:plannedStartDate, :datetime)
    field(:priority, Fhir.v6().CodeableConcept)
    field(:reason, [Fhir.v6().EncounterReason], default: [])
    field(:resourceType, :string, default: "Encounter")
    field(:serviceProvider, Fhir.v6().Reference)
    field(:serviceType, [Fhir.v6().CodeableReference], default: [])
    field(:specialArrangement, [Fhir.v6().CodeableConcept], default: [])
    field(:specialCourtesy, [Fhir.v6().CodeableConcept], default: [])
    field(:status, :string)
    field(:subject, Fhir.v6().Reference)
    field(:subjectStatus, Fhir.v6().CodeableConcept)
    field(:text, Fhir.v6().Narrative)
    field(:type, [Fhir.v6().CodeableConcept], default: [])
    field(:virtualService, [Fhir.v6().VirtualServiceDetail], default: [])
  end
end
