defmodule Fhir.v6().ExplanationOfBenefitItem do
  use TypedStruct

  typedstruct do
    field(:_careTeamSequence, [Fhir.v6().Element], default: [])
    field(:_diagnosisSequence, [Fhir.v6().Element], default: [])
    field(:_factor, Fhir.v6().Element)
    field(:_informationSequence, [Fhir.v6().Element], default: [])
    field(:_noteNumber, [Fhir.v6().Element], default: [])
    field(:_procedureSequence, [Fhir.v6().Element], default: [])
    field(:_sequence, Fhir.v6().Element)
    field(:_servicedDate, Fhir.v6().Element)
    field(:adjudication, [Fhir.v6().ExplanationOfBenefitAdjudication], default: [])
    field(:bodySite, [Fhir.v6().ExplanationOfBenefitBodySite], default: [])
    field(:careTeamSequence, [:float], default: [])
    field(:category, Fhir.v6().CodeableConcept)
    field(:detail, [Fhir.v6().ExplanationOfBenefitDetail], default: [])
    field(:diagnosisSequence, [:float], default: [])
    field(:encounter, [Fhir.v6().Reference], default: [])
    field(:extension, [Fhir.v6().Extension], default: [])
    field(:factor, :decimal)
    field(:id, :string)
    field(:informationSequence, [:float], default: [])
    field(:locationAddress, Fhir.v6().Address)
    field(:locationCodeableConcept, Fhir.v6().CodeableConcept)
    field(:locationReference, Fhir.v6().Reference)
    field(:modifier, [Fhir.v6().CodeableConcept], default: [])
    field(:modifierExtension, [Fhir.v6().Extension], default: [])
    field(:net, Fhir.v6().Money)
    field(:noteNumber, [:float], default: [])
    field(:patientPaid, Fhir.v6().Money)
    field(:procedureSequence, [:float], default: [])
    field(:productOrService, Fhir.v6().CodeableConcept)
    field(:productOrServiceEnd, Fhir.v6().CodeableConcept)
    field(:programCode, [Fhir.v6().CodeableConcept], default: [])
    field(:quantity, Fhir.v6().Quantity)
    field(:request, [Fhir.v6().Reference], default: [])
    field(:revenue, Fhir.v6().CodeableConcept)
    field(:reviewOutcome, Fhir.v6().ExplanationOfBenefitReviewOutcome)
    field(:sequence, :float)
    field(:servicedDate, :string)
    field(:servicedPeriod, Fhir.v6().Period)
    field(:tax, Fhir.v6().Money)
    field(:traceNumber, [Fhir.v6().Identifier], default: [])
    field(:udi, [Fhir.v6().Reference], default: [])
    field(:unitPrice, Fhir.v6().Money)
  end
end
