defmodule Fhir.v6().ExplanationOfBenefit do
  use TypedStruct

  typedstruct do
    field(:_created, Fhir.v6().Element)
    field(:_disposition, Fhir.v6().Element)
    field(:_implicitRules, Fhir.v6().Element)
    field(:_language, Fhir.v6().Element)
    field(:_outcome, Fhir.v6().Element)
    field(:_preAuthRef, [Fhir.v6().Element], default: [])
    field(:_precedence, Fhir.v6().Element)
    field(:_status, Fhir.v6().Element)
    field(:_use, Fhir.v6().Element)
    field(:accident, Fhir.v6().ExplanationOfBenefitAccident)
    field(:addItem, [Fhir.v6().ExplanationOfBenefitAddItem], default: [])
    field(:adjudication, [Fhir.v6().ExplanationOfBenefitAdjudication], default: [])
    field(:benefitBalance, [Fhir.v6().ExplanationOfBenefitBenefitBalance], default: [])
    field(:benefitPeriod, Fhir.v6().Period)
    field(:billablePeriod, Fhir.v6().Period)
    field(:careTeam, [Fhir.v6().ExplanationOfBenefitCareTeam], default: [])
    field(:claim, Fhir.v6().Reference)
    field(:claimResponse, Fhir.v6().Reference)
    field(:contained, [Fhir.v6().ResourceList], default: [])
    field(:created, :datetime)
    field(:decision, Fhir.v6().CodeableConcept)
    field(:diagnosis, [Fhir.v6().ExplanationOfBenefitDiagnosis], default: [])
    field(:diagnosisRelatedGroup, Fhir.v6().CodeableConcept)
    field(:disposition, :string)
    field(:encounter, [Fhir.v6().Reference], default: [])
    field(:enterer, Fhir.v6().Reference)
    field(:event, [Fhir.v6().ExplanationOfBenefitEvent], default: [])
    field(:extension, [Fhir.v6().Extension], default: [])
    field(:facility, Fhir.v6().Reference)
    field(:form, Fhir.v6().Attachment)
    field(:formCode, Fhir.v6().CodeableConcept)
    field(:fundsReserve, Fhir.v6().CodeableConcept)
    field(:fundsReserveRequested, Fhir.v6().CodeableConcept)
    field(:id, :string)
    field(:identifier, [Fhir.v6().Identifier], default: [])
    field(:implicitRules, :string)
    field(:insurance, [Fhir.v6().ExplanationOfBenefitInsurance], default: [])
    field(:insurer, Fhir.v6().Reference)
    field(:item, [Fhir.v6().ExplanationOfBenefitItem], default: [])
    field(:language, :string)
    field(:meta, Fhir.v6().Meta)
    field(:modifierExtension, [Fhir.v6().Extension], default: [])
    field(:originalPrescription, Fhir.v6().Reference)
    field(:outcome, :string)
    field(:patient, Fhir.v6().Reference)
    field(:patientPaid, Fhir.v6().Money)
    field(:payee, Fhir.v6().ExplanationOfBenefitPayee)
    field(:payment, Fhir.v6().ExplanationOfBenefitPayment)
    field(:preAuthRef, [:string], default: [])
    field(:preAuthRefPeriod, [Fhir.v6().Period], default: [])
    field(:precedence, :float)
    field(:prescription, Fhir.v6().Reference)
    field(:priority, Fhir.v6().CodeableConcept)
    field(:procedure, [Fhir.v6().ExplanationOfBenefitProcedure], default: [])
    field(:processNote, [Fhir.v6().ExplanationOfBenefitProcessNote], default: [])
    field(:provider, Fhir.v6().Reference)
    field(:referral, Fhir.v6().Reference)
    field(:related, [Fhir.v6().ExplanationOfBenefitRelated], default: [])
    field(:resourceType, :string, default: "ExplanationOfBenefit")
    field(:status, :string)
    field(:subType, Fhir.v6().CodeableConcept)
    field(:supportingInfo, [Fhir.v6().ExplanationOfBenefitSupportingInfo], default: [])
    field(:text, Fhir.v6().Narrative)
    field(:total, [Fhir.v6().ExplanationOfBenefitTotal], default: [])
    field(:traceNumber, [Fhir.v6().Identifier], default: [])
    field(:type, Fhir.v6().CodeableConcept)
    field(:use, :string)
  end
end
