defmodule Fhir.v6().FamilyMemberHistory do
  use TypedStruct

  typedstruct do
    field(:_ageString, Fhir.v6().Element)
    field(:_bornDate, Fhir.v6().Element)
    field(:_bornString, Fhir.v6().Element)
    field(:_date, Fhir.v6().Element)
    field(:_deceasedBoolean, Fhir.v6().Element)
    field(:_deceasedDate, Fhir.v6().Element)
    field(:_deceasedString, Fhir.v6().Element)
    field(:_estimatedAge, Fhir.v6().Element)
    field(:_implicitRules, Fhir.v6().Element)
    field(:_instantiatesUri, [Fhir.v6().Element], default: [])
    field(:_language, Fhir.v6().Element)
    field(:_name, Fhir.v6().Element)
    field(:_status, Fhir.v6().Element)
    field(:ageAge, Fhir.v6().Age)
    field(:ageRange, Fhir.v6().Range)
    field(:ageString, :string)
    field(:bornDate, :string)
    field(:bornPeriod, Fhir.v6().Period)
    field(:bornString, :string)
    field(:condition, [Fhir.v6().FamilyMemberHistoryCondition], default: [])
    field(:contained, [Fhir.v6().ResourceList], default: [])
    field(:dataAbsentReason, Fhir.v6().CodeableConcept)
    field(:date, :datetime)
    field(:deceasedAge, Fhir.v6().Age)
    field(:deceasedBoolean, :boolean)
    field(:deceasedDate, :string)
    field(:deceasedRange, Fhir.v6().Range)
    field(:deceasedString, :string)
    field(:estimatedAge, :boolean)
    field(:extension, [Fhir.v6().Extension], default: [])
    field(:id, :string)
    field(:identifier, [Fhir.v6().Identifier], default: [])
    field(:implicitRules, :string)
    field(:instantiatesCanonical, [:string], default: [])
    field(:instantiatesUri, [:string], default: [])
    field(:language, :string)
    field(:meta, Fhir.v6().Meta)
    field(:modifierExtension, [Fhir.v6().Extension], default: [])
    field(:name, :string)
    field(:note, [Fhir.v6().Annotation], default: [])
    field(:participant, [Fhir.v6().FamilyMemberHistoryParticipant], default: [])
    field(:patient, Fhir.v6().Reference)
    field(:procedure, [Fhir.v6().FamilyMemberHistoryProcedure], default: [])
    field(:reason, [Fhir.v6().CodeableReference], default: [])
    field(:relationship, Fhir.v6().CodeableConcept)
    field(:resourceType, :string, default: "FamilyMemberHistory")
    field(:sex, Fhir.v6().CodeableConcept)
    field(:status, :string)
    field(:text, Fhir.v6().Narrative)
  end
end
