defmodule Fhir.v6().Goal do
  use TypedStruct

  typedstruct do
    field(:_continuous, Fhir.v6().Element)
    field(:_implicitRules, Fhir.v6().Element)
    field(:_language, Fhir.v6().Element)
    field(:_lifecycleStatus, Fhir.v6().Element)
    field(:_startDate, Fhir.v6().Element)
    field(:_statusDate, Fhir.v6().Element)
    field(:_statusReason, Fhir.v6().Element)
    field(:achievementStatus, Fhir.v6().CodeableConcept)
    field(:addresses, [Fhir.v6().Reference], default: [])
    field(:category, [Fhir.v6().CodeableConcept], default: [])
    field(:contained, [Fhir.v6().ResourceList], default: [])
    field(:continuous, :boolean)
    field(:description, Fhir.v6().CodeableConcept)
    field(:extension, [Fhir.v6().Extension], default: [])
    field(:id, :string)
    field(:identifier, [Fhir.v6().Identifier], default: [])
    field(:implicitRules, :string)
    field(:language, :string)
    field(:lifecycleStatus, :string)
    field(:meta, Fhir.v6().Meta)
    field(:modifierExtension, [Fhir.v6().Extension], default: [])
    field(:note, [Fhir.v6().Annotation], default: [])
    field(:outcome, [Fhir.v6().CodeableReference], default: [])
    field(:priority, Fhir.v6().CodeableConcept)
    field(:resourceType, :string, default: "Goal")
    field(:source, Fhir.v6().Reference)
    field(:startCodeableConcept, Fhir.v6().CodeableConcept)
    field(:startDate, :string)
    field(:statusDate, :date)
    field(:statusReason, :string)
    field(:subject, Fhir.v6().Reference)
    field(:target, [Fhir.v6().GoalTarget], default: [])
    field(:text, Fhir.v6().Narrative)
  end
end
