defmodule Fhir.v6().HealthcareService do
  use TypedStruct

  typedstruct do
    field(:_active, Fhir.v6().Element)
    field(:_appointmentRequired, Fhir.v6().Element)
    field(:_comment, Fhir.v6().Element)
    field(:_extraDetails, Fhir.v6().Element)
    field(:_implicitRules, Fhir.v6().Element)
    field(:_language, Fhir.v6().Element)
    field(:_name, Fhir.v6().Element)
    field(:active, :boolean)
    field(:appointmentRequired, :boolean)
    field(:availability, [Fhir.v6().Availability], default: [])
    field(:category, [Fhir.v6().CodeableConcept], default: [])
    field(:characteristic, [Fhir.v6().CodeableConcept], default: [])
    field(:comment, :string)
    field(:communication, [Fhir.v6().CodeableConcept], default: [])
    field(:contact, [Fhir.v6().ExtendedContactDetail], default: [])
    field(:contained, [Fhir.v6().ResourceList], default: [])
    field(:coverageArea, [Fhir.v6().Reference], default: [])
    field(:eligibility, [Fhir.v6().HealthcareServiceEligibility], default: [])
    field(:endpoint, [Fhir.v6().Reference], default: [])
    field(:extension, [Fhir.v6().Extension], default: [])
    field(:extraDetails, :string)
    field(:id, :string)
    field(:identifier, [Fhir.v6().Identifier], default: [])
    field(:implicitRules, :string)
    field(:language, :string)
    field(:location, [Fhir.v6().Reference], default: [])
    field(:meta, Fhir.v6().Meta)
    field(:modifierExtension, [Fhir.v6().Extension], default: [])
    field(:name, :string)
    field(:offeredIn, [Fhir.v6().Reference], default: [])
    field(:photo, Fhir.v6().Attachment)
    field(:program, [Fhir.v6().CodeableConcept], default: [])
    field(:providedBy, Fhir.v6().Reference)
    field(:referralMethod, [Fhir.v6().CodeableConcept], default: [])
    field(:resourceType, :string, default: "HealthcareService")
    field(:serviceProvisionCode, [Fhir.v6().CodeableConcept], default: [])
    field(:specialty, [Fhir.v6().CodeableConcept], default: [])
    field(:text, Fhir.v6().Narrative)
    field(:type, [Fhir.v6().CodeableConcept], default: [])
  end
end
