defmodule Fhir.v6().ImagingSelection do
  use TypedStruct

  typedstruct do
    field(:_frameOfReferenceUid, Fhir.v6().Element)
    field(:_implicitRules, Fhir.v6().Element)
    field(:_issued, Fhir.v6().Element)
    field(:_language, Fhir.v6().Element)
    field(:_seriesNumber, Fhir.v6().Element)
    field(:_seriesUid, Fhir.v6().Element)
    field(:_status, Fhir.v6().Element)
    field(:_studyUid, Fhir.v6().Element)
    field(:basedOn, [Fhir.v6().Reference], default: [])
    field(:bodySite, Fhir.v6().CodeableReference)
    field(:category, [Fhir.v6().CodeableConcept], default: [])
    field(:code, Fhir.v6().CodeableConcept)
    field(:contained, [Fhir.v6().ResourceList], default: [])
    field(:derivedFrom, [Fhir.v6().Reference], default: [])
    field(:endpoint, [Fhir.v6().Reference], default: [])
    field(:extension, [Fhir.v6().Extension], default: [])
    field(:focus, [Fhir.v6().Reference], default: [])
    field(:frameOfReferenceUid, :string)
    field(:id, :string)
    field(:identifier, [Fhir.v6().Identifier], default: [])
    field(:implicitRules, :string)
    field(:instance, [Fhir.v6().ImagingSelectionInstance], default: [])
    field(:issued, :timestamp)
    field(:language, :string)
    field(:meta, Fhir.v6().Meta)
    field(:modifierExtension, [Fhir.v6().Extension], default: [])
    field(:performer, [Fhir.v6().ImagingSelectionPerformer], default: [])
    field(:resourceType, :string, default: "ImagingSelection")
    field(:seriesNumber, :float)
    field(:seriesUid, :string)
    field(:status, :string)
    field(:studyUid, :string)
    field(:subject, Fhir.v6().Reference)
    field(:text, Fhir.v6().Narrative)
  end
end
