defmodule Fhir.v6().ImagingStudy do
  use TypedStruct

  typedstruct do
    field(:_description, Fhir.v6().Element)
    field(:_implicitRules, Fhir.v6().Element)
    field(:_language, Fhir.v6().Element)
    field(:_numberOfInstances, Fhir.v6().Element)
    field(:_numberOfSeries, Fhir.v6().Element)
    field(:_started, Fhir.v6().Element)
    field(:_status, Fhir.v6().Element)
    field(:basedOn, [Fhir.v6().Reference], default: [])
    field(:contained, [Fhir.v6().ResourceList], default: [])
    field(:description, :string)
    field(:encounter, Fhir.v6().Reference)
    field(:endpoint, [Fhir.v6().Reference], default: [])
    field(:extension, [Fhir.v6().Extension], default: [])
    field(:id, :string)
    field(:identifier, [Fhir.v6().Identifier], default: [])
    field(:implicitRules, :string)
    field(:language, :string)
    field(:location, Fhir.v6().Reference)
    field(:meta, Fhir.v6().Meta)
    field(:modality, [Fhir.v6().CodeableConcept], default: [])
    field(:modifierExtension, [Fhir.v6().Extension], default: [])
    field(:note, [Fhir.v6().Annotation], default: [])
    field(:numberOfInstances, :float)
    field(:numberOfSeries, :float)
    field(:partOf, [Fhir.v6().Reference], default: [])
    field(:procedure, [Fhir.v6().CodeableReference], default: [])
    field(:reason, [Fhir.v6().CodeableReference], default: [])
    field(:referrer, Fhir.v6().Reference)
    field(:resourceType, :string, default: "ImagingStudy")
    field(:series, [Fhir.v6().ImagingStudySeries], default: [])
    field(:started, :datetime)
    field(:status, :string)
    field(:subject, Fhir.v6().Reference)
    field(:text, Fhir.v6().Narrative)
  end
end
