defmodule Fhir.v6().ImplementationGuide do
  use TypedStruct

  typedstruct do
    field(:_copyright, Fhir.v6().Element)
    field(:_copyrightLabel, Fhir.v6().Element)
    field(:_date, Fhir.v6().Element)
    field(:_description, Fhir.v6().Element)
    field(:_experimental, Fhir.v6().Element)
    field(:_fhirVersion, [Fhir.v6().Element], default: [])
    field(:_implicitRules, Fhir.v6().Element)
    field(:_language, Fhir.v6().Element)
    field(:_license, Fhir.v6().Element)
    field(:_name, Fhir.v6().Element)
    field(:_packageId, Fhir.v6().Element)
    field(:_publisher, Fhir.v6().Element)
    field(:_purpose, Fhir.v6().Element)
    field(:_status, Fhir.v6().Element)
    field(:_title, Fhir.v6().Element)
    field(:_url, Fhir.v6().Element)
    field(:_version, Fhir.v6().Element)
    field(:_versionAlgorithmString, Fhir.v6().Element)
    field(:contact, [Fhir.v6().ContactDetail], default: [])
    field(:contained, [Fhir.v6().ResourceList], default: [])
    field(:copyright, :string)
    field(:copyrightLabel, :string)
    field(:date, :datetime)
    field(:definition, Fhir.v6().ImplementationGuideDefinition)
    field(:dependsOn, [Fhir.v6().ImplementationGuideDependsOn], default: [])
    field(:description, :string)
    field(:experimental, :boolean)
    field(:extension, [Fhir.v6().Extension], default: [])
    field(:fhirVersion, [:string], default: [])
    field(:global, [Fhir.v6().ImplementationGuideGlobal], default: [])
    field(:id, :string)
    field(:identifier, [Fhir.v6().Identifier], default: [])
    field(:implicitRules, :string)
    field(:jurisdiction, [Fhir.v6().CodeableConcept], default: [])
    field(:language, :string)
    field(:license, :string)
    field(:manifest, Fhir.v6().ImplementationGuideManifest)
    field(:meta, Fhir.v6().Meta)
    field(:modifierExtension, [Fhir.v6().Extension], default: [])
    field(:name, :string)
    field(:packageId, :string)
    field(:publisher, :string)
    field(:purpose, :string)
    field(:resourceType, :string, default: "ImplementationGuide")
    field(:status, :string)
    field(:text, Fhir.v6().Narrative)
    field(:title, :string)
    field(:url, :string)
    field(:useContext, [Fhir.v6().UsageContext], default: [])
    field(:version, :string)
    field(:versionAlgorithmCoding, Fhir.v6().Coding)
    field(:versionAlgorithmString, :string)
  end
end
