defmodule Fhir.v6().Invoice do
  use TypedStruct

  typedstruct do
    field(:_cancelledReason, Fhir.v6().Element)
    field(:_creation, Fhir.v6().Element)
    field(:_date, Fhir.v6().Element)
    field(:_implicitRules, Fhir.v6().Element)
    field(:_language, Fhir.v6().Element)
    field(:_paymentTerms, Fhir.v6().Element)
    field(:_periodDate, Fhir.v6().Element)
    field(:_status, Fhir.v6().Element)
    field(:account, Fhir.v6().Reference)
    field(:cancelledReason, :string)
    field(:contained, [Fhir.v6().ResourceList], default: [])
    field(:creation, :datetime)
    field(:date, :datetime)
    field(:extension, [Fhir.v6().Extension], default: [])
    field(:id, :string)
    field(:identifier, [Fhir.v6().Identifier], default: [])
    field(:implicitRules, :string)
    field(:issuer, Fhir.v6().Reference)
    field(:language, :string)
    field(:lineItem, [Fhir.v6().InvoiceLineItem], default: [])
    field(:meta, Fhir.v6().Meta)
    field(:modifierExtension, [Fhir.v6().Extension], default: [])
    field(:note, [Fhir.v6().Annotation], default: [])
    field(:participant, [Fhir.v6().InvoiceParticipant], default: [])
    field(:paymentTerms, :string)
    field(:periodDate, :string)
    field(:periodPeriod, Fhir.v6().Period)
    field(:recipient, Fhir.v6().Reference)
    field(:resourceType, :string, default: "Invoice")
    field(:status, :string)
    field(:subject, Fhir.v6().Reference)
    field(:text, Fhir.v6().Narrative)
    field(:totalGross, Fhir.v6().Money)
    field(:totalNet, Fhir.v6().Money)
    field(:totalPriceComponent, [Fhir.v6().MonetaryComponent], default: [])
    field(:type, Fhir.v6().CodeableConcept)
  end
end
