defmodule Fhir.v6().Location do
  use TypedStruct

  typedstruct do
    field(:_alias, [Fhir.v6().Element], default: [])
    field(:_description, Fhir.v6().Element)
    field(:_implicitRules, Fhir.v6().Element)
    field(:_language, Fhir.v6().Element)
    field(:_mode, Fhir.v6().Element)
    field(:_name, Fhir.v6().Element)
    field(:_status, Fhir.v6().Element)
    field(:address, Fhir.v6().Address)
    field(:alias, [:string], default: [])
    field(:characteristic, [Fhir.v6().CodeableConcept], default: [])
    field(:contact, [Fhir.v6().ExtendedContactDetail], default: [])
    field(:contained, [Fhir.v6().ResourceList], default: [])
    field(:description, :string)
    field(:endpoint, [Fhir.v6().Reference], default: [])
    field(:extension, [Fhir.v6().Extension], default: [])
    field(:form, Fhir.v6().CodeableConcept)
    field(:hoursOfOperation, [Fhir.v6().Availability], default: [])
    field(:id, :string)
    field(:identifier, [Fhir.v6().Identifier], default: [])
    field(:implicitRules, :string)
    field(:language, :string)
    field(:managingOrganization, Fhir.v6().Reference)
    field(:meta, Fhir.v6().Meta)
    field(:mode, :string)
    field(:modifierExtension, [Fhir.v6().Extension], default: [])
    field(:name, :string)
    field(:operationalStatus, Fhir.v6().Coding)
    field(:partOf, Fhir.v6().Reference)
    field(:position, Fhir.v6().LocationPosition)
    field(:resourceType, :string, default: "Location")
    field(:status, :string)
    field(:text, Fhir.v6().Narrative)
    field(:type, [Fhir.v6().CodeableConcept], default: [])
    field(:virtualService, [Fhir.v6().VirtualServiceDetail], default: [])
  end
end
