defmodule Fhir.v6().Measure do
  use TypedStruct

  typedstruct do
    field(:_approvalDate, Fhir.v6().Element)
    field(:_basis, Fhir.v6().Element)
    field(:_clinicalRecommendationStatement, Fhir.v6().Element)
    field(:_copyright, Fhir.v6().Element)
    field(:_copyrightLabel, Fhir.v6().Element)
    field(:_date, Fhir.v6().Element)
    field(:_description, Fhir.v6().Element)
    field(:_disclaimer, Fhir.v6().Element)
    field(:_experimental, Fhir.v6().Element)
    field(:_guidance, Fhir.v6().Element)
    field(:_implicitRules, Fhir.v6().Element)
    field(:_language, Fhir.v6().Element)
    field(:_lastReviewDate, Fhir.v6().Element)
    field(:_name, Fhir.v6().Element)
    field(:_publisher, Fhir.v6().Element)
    field(:_purpose, Fhir.v6().Element)
    field(:_rateAggregation, Fhir.v6().Element)
    field(:_rationale, Fhir.v6().Element)
    field(:_riskAdjustment, Fhir.v6().Element)
    field(:_status, Fhir.v6().Element)
    field(:_subtitle, Fhir.v6().Element)
    field(:_title, Fhir.v6().Element)
    field(:_url, Fhir.v6().Element)
    field(:_usage, Fhir.v6().Element)
    field(:_version, Fhir.v6().Element)
    field(:_versionAlgorithmString, Fhir.v6().Element)
    field(:approvalDate, :date)
    field(:author, [Fhir.v6().ContactDetail], default: [])
    field(:basis, :string)
    field(:clinicalRecommendationStatement, :string)
    field(:compositeScoring, Fhir.v6().CodeableConcept)
    field(:contact, [Fhir.v6().ContactDetail], default: [])
    field(:contained, [Fhir.v6().ResourceList], default: [])
    field(:copyright, :string)
    field(:copyrightLabel, :string)
    field(:date, :datetime)
    field(:description, :string)
    field(:disclaimer, :string)
    field(:editor, [Fhir.v6().ContactDetail], default: [])
    field(:effectivePeriod, Fhir.v6().Period)
    field(:endorser, [Fhir.v6().ContactDetail], default: [])
    field(:experimental, :boolean)
    field(:extension, [Fhir.v6().Extension], default: [])
    field(:group, [Fhir.v6().MeasureGroup], default: [])
    field(:guidance, :string)
    field(:id, :string)
    field(:identifier, [Fhir.v6().Identifier], default: [])
    field(:implicitRules, :string)
    field(:improvementNotation, Fhir.v6().CodeableConcept)
    field(:jurisdiction, [Fhir.v6().CodeableConcept], default: [])
    field(:language, :string)
    field(:lastReviewDate, :date)
    field(:library, [:string], default: [])
    field(:meta, Fhir.v6().Meta)
    field(:modifierExtension, [Fhir.v6().Extension], default: [])
    field(:name, :string)
    field(:publisher, :string)
    field(:purpose, :string)
    field(:rateAggregation, :string)
    field(:rationale, :string)
    field(:relatedArtifact, [Fhir.v6().RelatedArtifact], default: [])
    field(:resourceType, :string, default: "Measure")
    field(:reviewer, [Fhir.v6().ContactDetail], default: [])
    field(:riskAdjustment, :string)
    field(:scoring, Fhir.v6().CodeableConcept)
    field(:scoringUnit, Fhir.v6().CodeableConcept)
    field(:status, :string)
    field(:subjectCodeableConcept, Fhir.v6().CodeableConcept)
    field(:subjectReference, Fhir.v6().Reference)
    field(:subtitle, :string)
    field(:supplementalData, [Fhir.v6().MeasureSupplementalData], default: [])
    field(:term, [Fhir.v6().MeasureTerm], default: [])
    field(:text, Fhir.v6().Narrative)
    field(:title, :string)
    field(:topic, [Fhir.v6().CodeableConcept], default: [])
    field(:type, [Fhir.v6().CodeableConcept], default: [])
    field(:url, :string)
    field(:usage, :string)
    field(:useContext, [Fhir.v6().UsageContext], default: [])
    field(:version, :string)
    field(:versionAlgorithmCoding, Fhir.v6().Coding)
    field(:versionAlgorithmString, :string)
  end
end
