defmodule Fhir.v6().MedicationRequest do
  use TypedStruct

  typedstruct do
    field(:_authoredOn, Fhir.v6().Element)
    field(:_doNotPerform, Fhir.v6().Element)
    field(:_implicitRules, Fhir.v6().Element)
    field(:_intent, Fhir.v6().Element)
    field(:_language, Fhir.v6().Element)
    field(:_priority, Fhir.v6().Element)
    field(:_renderedDosageInstruction, Fhir.v6().Element)
    field(:_reported, Fhir.v6().Element)
    field(:_status, Fhir.v6().Element)
    field(:_statusChanged, Fhir.v6().Element)
    field(:authoredOn, :datetime)
    field(:basedOn, [Fhir.v6().Reference], default: [])
    field(:category, [Fhir.v6().CodeableConcept], default: [])
    field(:contained, [Fhir.v6().ResourceList], default: [])
    field(:courseOfTherapyType, Fhir.v6().CodeableConcept)
    field(:device, [Fhir.v6().CodeableReference], default: [])
    field(:dispenseRequest, Fhir.v6().MedicationRequestDispenseRequest)
    field(:doNotPerform, :boolean)
    field(:dosageInstruction, [Fhir.v6().Dosage], default: [])
    field(:effectiveDosePeriod, Fhir.v6().Period)
    field(:encounter, Fhir.v6().Reference)
    field(:eventHistory, [Fhir.v6().Reference], default: [])
    field(:extension, [Fhir.v6().Extension], default: [])
    field(:groupIdentifier, Fhir.v6().Identifier)
    field(:id, :string)
    field(:identifier, [Fhir.v6().Identifier], default: [])
    field(:implicitRules, :string)
    field(:informationSource, [Fhir.v6().Reference], default: [])
    field(:insurance, [Fhir.v6().Reference], default: [])
    field(:intent, :string)
    field(:language, :string)
    field(:medication, Fhir.v6().CodeableReference)
    field(:meta, Fhir.v6().Meta)
    field(:modifierExtension, [Fhir.v6().Extension], default: [])
    field(:note, [Fhir.v6().Annotation], default: [])
    field(:performer, [Fhir.v6().Reference], default: [])
    field(:performerType, Fhir.v6().CodeableConcept)
    field(:priorPrescription, Fhir.v6().Reference)
    field(:priority, :string)
    field(:reason, [Fhir.v6().CodeableReference], default: [])
    field(:recorder, Fhir.v6().Reference)
    field(:renderedDosageInstruction, :string)
    field(:reported, :boolean)
    field(:requester, Fhir.v6().Reference)
    field(:resourceType, :string, default: "MedicationRequest")
    field(:status, :string)
    field(:statusChanged, :datetime)
    field(:statusReason, Fhir.v6().CodeableConcept)
    field(:subject, Fhir.v6().Reference)
    field(:substitution, Fhir.v6().MedicationRequestSubstitution)
    field(:supportingInformation, [Fhir.v6().Reference], default: [])
    field(:text, Fhir.v6().Narrative)
  end
end
