defmodule Fhir.v6().MedicationKnowledge do
  use TypedStruct

  typedstruct do
    field(:_approvalDate, Fhir.v6().Element)
    field(:_copyright, Fhir.v6().Element)
    field(:_copyrightLabel, Fhir.v6().Element)
    field(:_date, Fhir.v6().Element)
    field(:_description, Fhir.v6().Element)
    field(:_experimental, Fhir.v6().Element)
    field(:_implicitRules, Fhir.v6().Element)
    field(:_language, Fhir.v6().Element)
    field(:_lastReviewDate, Fhir.v6().Element)
    field(:_name, [Fhir.v6().Element], default: [])
    field(:_preparationInstruction, Fhir.v6().Element)
    field(:_publisher, Fhir.v6().Element)
    field(:_purpose, Fhir.v6().Element)
    field(:_status, Fhir.v6().Element)
    field(:_title, Fhir.v6().Element)
    field(:_url, Fhir.v6().Element)
    field(:_version, Fhir.v6().Element)
    field(:_versionAlgorithmString, Fhir.v6().Element)
    field(:approvalDate, :date)
    field(:associatedMedication, [Fhir.v6().Reference], default: [])
    field(:author, Fhir.v6().Reference)
    field(:clinicalUseIssue, [Fhir.v6().Reference], default: [])
    field(:code, Fhir.v6().CodeableConcept)
    field(:contact, [Fhir.v6().ContactDetail], default: [])
    field(:contained, [Fhir.v6().ResourceList], default: [])
    field(:copyright, :string)
    field(:copyrightLabel, :string)
    field(:cost, [Fhir.v6().MedicationKnowledgeCost], default: [])
    field(:date, :datetime)
    field(:definitional, Fhir.v6().MedicationKnowledgeDefinitional)
    field(:description, :string)
    field(:editor, [Fhir.v6().ContactDetail], default: [])
    field(:effectivePeriod, Fhir.v6().Period)
    field(:endorser, [Fhir.v6().ContactDetail], default: [])
    field(:experimental, :boolean)
    field(:extension, [Fhir.v6().Extension], default: [])
    field(:id, :string)
    field(:identifier, [Fhir.v6().Identifier], default: [])
    field(:implicitRules, :string)
    field(:indicationGuideline, [Fhir.v6().MedicationKnowledgeIndicationGuideline], default: [])
    field(:intendedJurisdiction, [Fhir.v6().CodeableConcept], default: [])
    field(:jurisdiction, [Fhir.v6().CodeableConcept], default: [])
    field(:language, :string)
    field(:lastReviewDate, :date)

    field(:medicineClassification, [Fhir.v6().MedicationKnowledgeMedicineClassification],
      default: []
    )

    field(:meta, Fhir.v6().Meta)
    field(:modifierExtension, [Fhir.v6().Extension], default: [])
    field(:monitoringProgram, [Fhir.v6().MedicationKnowledgeMonitoringProgram], default: [])
    field(:monograph, [Fhir.v6().MedicationKnowledgeMonograph], default: [])
    field(:name, [:string], default: [])
    field(:packaging, [Fhir.v6().MedicationKnowledgePackaging], default: [])
    field(:preparationInstruction, :string)
    field(:productType, [Fhir.v6().CodeableConcept], default: [])
    field(:publisher, :string)
    field(:purpose, :string)
    field(:regulatory, [Fhir.v6().MedicationKnowledgeRegulatory], default: [])
    field(:relatedArtifact, [Fhir.v6().RelatedArtifact], default: [])

    field(:relatedMedicationKnowledge, [Fhir.v6().MedicationKnowledgeRelatedMedicationKnowledge],
      default: []
    )

    field(:resourceType, :string, default: "MedicationKnowledge")
    field(:reviewer, [Fhir.v6().ContactDetail], default: [])
    field(:status, :string)
    field(:storageGuideline, [Fhir.v6().MedicationKnowledgeStorageGuideline], default: [])
    field(:text, Fhir.v6().Narrative)
    field(:title, :string)
    field(:topic, [Fhir.v6().CodeableConcept], default: [])
    field(:url, :string)
    field(:useContext, [Fhir.v6().UsageContext], default: [])
    field(:version, :string)
    field(:versionAlgorithmCoding, Fhir.v6().Coding)
    field(:versionAlgorithmString, :string)
  end
end
