defmodule Fhir.v6().MedicationAdministration do
  use TypedStruct

  typedstruct do
    field(:_implicitRules, Fhir.v6().Element)
    field(:_isSubPotent, Fhir.v6().Element)
    field(:_language, Fhir.v6().Element)
    field(:_occurenceDateTime, Fhir.v6().Element)
    field(:_recorded, Fhir.v6().Element)
    field(:_status, Fhir.v6().Element)
    field(:basedOn, [Fhir.v6().Reference], default: [])
    field(:category, [Fhir.v6().CodeableConcept], default: [])
    field(:contained, [Fhir.v6().ResourceList], default: [])
    field(:device, [Fhir.v6().CodeableReference], default: [])
    field(:dosage, Fhir.v6().MedicationAdministrationDosage)
    field(:encounter, Fhir.v6().Reference)
    field(:eventHistory, [Fhir.v6().Reference], default: [])
    field(:extension, [Fhir.v6().Extension], default: [])
    field(:id, :string)
    field(:identifier, [Fhir.v6().Identifier], default: [])
    field(:implicitRules, :string)
    field(:isSubPotent, :boolean)
    field(:language, :string)
    field(:medication, Fhir.v6().CodeableReference)
    field(:meta, Fhir.v6().Meta)
    field(:modifierExtension, [Fhir.v6().Extension], default: [])
    field(:note, [Fhir.v6().Annotation], default: [])
    field(:occurenceDateTime, :string)
    field(:occurencePeriod, Fhir.v6().Period)
    field(:occurenceTiming, Fhir.v6().Timing)
    field(:partOf, [Fhir.v6().Reference], default: [])
    field(:performer, [Fhir.v6().MedicationAdministrationPerformer], default: [])
    field(:reason, [Fhir.v6().CodeableReference], default: [])
    field(:recorded, :datetime)
    field(:request, Fhir.v6().Reference)
    field(:resourceType, :string, default: "MedicationAdministration")
    field(:status, :string)
    field(:statusReason, [Fhir.v6().CodeableConcept], default: [])
    field(:subPotentReason, [Fhir.v6().CodeableConcept], default: [])
    field(:subject, Fhir.v6().Reference)
    field(:supportingInformation, [Fhir.v6().Reference], default: [])
    field(:text, Fhir.v6().Narrative)
  end
end
