defmodule Fhir.v6().MedicationDispense do
  use TypedStruct

  typedstruct do
    field(:_implicitRules, Fhir.v6().Element)
    field(:_language, Fhir.v6().Element)
    field(:_recorded, Fhir.v6().Element)
    field(:_renderedDosageInstruction, Fhir.v6().Element)
    field(:_status, Fhir.v6().Element)
    field(:_statusChanged, Fhir.v6().Element)
    field(:_whenHandedOver, Fhir.v6().Element)
    field(:_whenPrepared, Fhir.v6().Element)
    field(:authorizingPrescription, [Fhir.v6().Reference], default: [])
    field(:basedOn, [Fhir.v6().Reference], default: [])
    field(:category, [Fhir.v6().CodeableConcept], default: [])
    field(:contained, [Fhir.v6().ResourceList], default: [])
    field(:daysSupply, Fhir.v6().Quantity)
    field(:destination, Fhir.v6().Reference)
    field(:dosageInstruction, [Fhir.v6().Dosage], default: [])
    field(:encounter, Fhir.v6().Reference)
    field(:eventHistory, [Fhir.v6().Reference], default: [])
    field(:extension, [Fhir.v6().Extension], default: [])
    field(:id, :string)
    field(:identifier, [Fhir.v6().Identifier], default: [])
    field(:implicitRules, :string)
    field(:language, :string)
    field(:location, Fhir.v6().Reference)
    field(:medication, Fhir.v6().CodeableReference)
    field(:meta, Fhir.v6().Meta)
    field(:modifierExtension, [Fhir.v6().Extension], default: [])
    field(:notPerformedReason, Fhir.v6().CodeableReference)
    field(:note, [Fhir.v6().Annotation], default: [])
    field(:partOf, [Fhir.v6().Reference], default: [])
    field(:performer, [Fhir.v6().MedicationDispensePerformer], default: [])
    field(:quantity, Fhir.v6().Quantity)
    field(:receiver, [Fhir.v6().Reference], default: [])
    field(:recorded, :datetime)
    field(:renderedDosageInstruction, :string)
    field(:resourceType, :string, default: "MedicationDispense")
    field(:status, :string)
    field(:statusChanged, :datetime)
    field(:subject, Fhir.v6().Reference)
    field(:substitution, Fhir.v6().MedicationDispenseSubstitution)
    field(:supportingInformation, [Fhir.v6().Reference], default: [])
    field(:text, Fhir.v6().Narrative)
    field(:type, Fhir.v6().CodeableConcept)
    field(:whenHandedOver, :datetime)
    field(:whenPrepared, :datetime)
  end
end
