defmodule Fhir.v6().MedicinalProductDefinition do
  use TypedStruct

  typedstruct do
    field(:_description, Fhir.v6().Element)
    field(:_implicitRules, Fhir.v6().Element)
    field(:_indication, Fhir.v6().Element)
    field(:_language, Fhir.v6().Element)
    field(:_statusDate, Fhir.v6().Element)
    field(:_version, Fhir.v6().Element)
    field(:additionalMonitoringIndicator, Fhir.v6().CodeableConcept)
    field(:attachedDocument, [Fhir.v6().Reference], default: [])
    field(:characteristic, [Fhir.v6().MedicinalProductDefinitionCharacteristic], default: [])
    field(:classification, [Fhir.v6().CodeableConcept], default: [])
    field(:clinicalTrial, [Fhir.v6().Reference], default: [])
    field(:code, [Fhir.v6().Coding], default: [])
    field(:combinedPharmaceuticalDoseForm, Fhir.v6().CodeableConcept)
    field(:comprisedOf, [Fhir.v6().Reference], default: [])
    field(:contact, [Fhir.v6().MedicinalProductDefinitionContact], default: [])
    field(:contained, [Fhir.v6().ResourceList], default: [])
    field(:crossReference, [Fhir.v6().MedicinalProductDefinitionCrossReference], default: [])
    field(:description, :string)
    field(:domain, Fhir.v6().CodeableConcept)
    field(:extension, [Fhir.v6().Extension], default: [])
    field(:id, :string)
    field(:identifier, [Fhir.v6().Identifier], default: [])
    field(:implicitRules, :string)
    field(:impurity, [Fhir.v6().CodeableReference], default: [])
    field(:indication, :string)
    field(:ingredient, [Fhir.v6().CodeableConcept], default: [])
    field(:language, :string)
    field(:legalStatusOfSupply, Fhir.v6().CodeableConcept)
    field(:marketingStatus, [Fhir.v6().MarketingStatus], default: [])
    field(:masterFile, [Fhir.v6().Reference], default: [])
    field(:meta, Fhir.v6().Meta)
    field(:modifierExtension, [Fhir.v6().Extension], default: [])
    field(:name, [Fhir.v6().MedicinalProductDefinitionName], default: [])
    field(:operation, [Fhir.v6().MedicinalProductDefinitionOperation], default: [])
    field(:packagedMedicinalProduct, [Fhir.v6().CodeableConcept], default: [])
    field(:pediatricUseIndicator, Fhir.v6().CodeableConcept)
    field(:resourceType, :string, default: "MedicinalProductDefinition")
    field(:route, [Fhir.v6().CodeableConcept], default: [])
    field(:specialMeasures, [Fhir.v6().CodeableConcept], default: [])
    field(:status, Fhir.v6().CodeableConcept)
    field(:statusDate, :datetime)
    field(:text, Fhir.v6().Narrative)
    field(:type, Fhir.v6().CodeableConcept)
    field(:version, :string)
  end
end
