defmodule Fhir.v6().MessageDefinition do
  use TypedStruct

  typedstruct do
    field(:_category, Fhir.v6().Element)
    field(:_copyright, Fhir.v6().Element)
    field(:_copyrightLabel, Fhir.v6().Element)
    field(:_date, Fhir.v6().Element)
    field(:_description, Fhir.v6().Element)
    field(:_eventUri, Fhir.v6().Element)
    field(:_experimental, Fhir.v6().Element)
    field(:_implicitRules, Fhir.v6().Element)
    field(:_language, Fhir.v6().Element)
    field(:_name, Fhir.v6().Element)
    field(:_publisher, Fhir.v6().Element)
    field(:_purpose, Fhir.v6().Element)
    field(:_responseRequired, Fhir.v6().Element)
    field(:_status, Fhir.v6().Element)
    field(:_title, Fhir.v6().Element)
    field(:_url, Fhir.v6().Element)
    field(:_version, Fhir.v6().Element)
    field(:_versionAlgorithmString, Fhir.v6().Element)
    field(:allowedResponse, [Fhir.v6().MessageDefinitionAllowedResponse], default: [])
    field(:base, :string)
    field(:category, :string)
    field(:contact, [Fhir.v6().ContactDetail], default: [])
    field(:contained, [Fhir.v6().ResourceList], default: [])
    field(:copyright, :string)
    field(:copyrightLabel, :string)
    field(:date, :datetime)
    field(:description, :string)
    field(:eventCoding, Fhir.v6().Coding)
    field(:eventUri, :string)
    field(:experimental, :boolean)
    field(:extension, [Fhir.v6().Extension], default: [])
    field(:focus, [Fhir.v6().MessageDefinitionFocus], default: [])
    field(:graph, :string)
    field(:id, :string)
    field(:identifier, [Fhir.v6().Identifier], default: [])
    field(:implicitRules, :string)
    field(:jurisdiction, [Fhir.v6().CodeableConcept], default: [])
    field(:language, :string)
    field(:meta, Fhir.v6().Meta)
    field(:modifierExtension, [Fhir.v6().Extension], default: [])
    field(:name, :string)
    field(:parent, [:string], default: [])
    field(:publisher, :string)
    field(:purpose, :string)
    field(:replaces, [:string], default: [])
    field(:resourceType, :string, default: "MessageDefinition")
    field(:responseRequired, :string)
    field(:status, :string)
    field(:text, Fhir.v6().Narrative)
    field(:title, :string)
    field(:url, :string)
    field(:useContext, [Fhir.v6().UsageContext], default: [])
    field(:version, :string)
    field(:versionAlgorithmCoding, Fhir.v6().Coding)
    field(:versionAlgorithmString, :string)
  end
end
