defmodule Fhir.v6().NutritionIntake do
  use TypedStruct

  typedstruct do
    field(:_implicitRules, Fhir.v6().Element)
    field(:_instantiatesUri, [Fhir.v6().Element], default: [])
    field(:_language, Fhir.v6().Element)
    field(:_occurrenceDateTime, Fhir.v6().Element)
    field(:_recorded, Fhir.v6().Element)
    field(:_reportedBoolean, Fhir.v6().Element)
    field(:_status, Fhir.v6().Element)
    field(:basedOn, [Fhir.v6().Reference], default: [])
    field(:code, Fhir.v6().CodeableConcept)
    field(:consumedItem, [Fhir.v6().NutritionIntakeConsumedItem], default: [])
    field(:contained, [Fhir.v6().ResourceList], default: [])
    field(:derivedFrom, [Fhir.v6().Reference], default: [])
    field(:encounter, Fhir.v6().Reference)
    field(:extension, [Fhir.v6().Extension], default: [])
    field(:id, :string)
    field(:identifier, [Fhir.v6().Identifier], default: [])
    field(:implicitRules, :string)
    field(:ingredientLabel, [Fhir.v6().NutritionIntakeIngredientLabel], default: [])
    field(:instantiatesCanonical, [:string], default: [])
    field(:instantiatesUri, [:string], default: [])
    field(:language, :string)
    field(:location, Fhir.v6().Reference)
    field(:meta, Fhir.v6().Meta)
    field(:modifierExtension, [Fhir.v6().Extension], default: [])
    field(:note, [Fhir.v6().Annotation], default: [])
    field(:occurrenceDateTime, :string)
    field(:occurrencePeriod, Fhir.v6().Period)
    field(:partOf, [Fhir.v6().Reference], default: [])
    field(:performer, [Fhir.v6().NutritionIntakePerformer], default: [])
    field(:reason, [Fhir.v6().CodeableReference], default: [])
    field(:recorded, :datetime)
    field(:reportedBoolean, :boolean)
    field(:reportedReference, Fhir.v6().Reference)
    field(:resourceType, :string, default: "NutritionIntake")
    field(:status, :string)
    field(:statusReason, [Fhir.v6().CodeableConcept], default: [])
    field(:subject, Fhir.v6().Reference)
    field(:text, Fhir.v6().Narrative)
  end
end
