defmodule Fhir.v6().NutritionOrder do
  use TypedStruct

  typedstruct do
    field(:_dateTime, Fhir.v6().Element)
    field(:_implicitRules, Fhir.v6().Element)
    field(:_instantiates, [Fhir.v6().Element], default: [])
    field(:_instantiatesUri, [Fhir.v6().Element], default: [])
    field(:_intent, Fhir.v6().Element)
    field(:_language, Fhir.v6().Element)
    field(:_outsideFoodAllowed, Fhir.v6().Element)
    field(:_priority, Fhir.v6().Element)
    field(:_status, Fhir.v6().Element)
    field(:allergyIntolerance, [Fhir.v6().Reference], default: [])
    field(:basedOn, [Fhir.v6().Reference], default: [])
    field(:contained, [Fhir.v6().ResourceList], default: [])
    field(:dateTime, :datetime)
    field(:encounter, Fhir.v6().Reference)
    field(:enteralFormula, Fhir.v6().NutritionOrderEnteralFormula)
    field(:excludeFoodModifier, [Fhir.v6().CodeableConcept], default: [])
    field(:extension, [Fhir.v6().Extension], default: [])
    field(:foodPreferenceModifier, [Fhir.v6().CodeableConcept], default: [])
    field(:groupIdentifier, Fhir.v6().Identifier)
    field(:id, :string)
    field(:identifier, [Fhir.v6().Identifier], default: [])
    field(:implicitRules, :string)
    field(:instantiates, [:string], default: [])
    field(:instantiatesCanonical, [:string], default: [])
    field(:instantiatesUri, [:string], default: [])
    field(:intent, :string)
    field(:language, :string)
    field(:meta, Fhir.v6().Meta)
    field(:modifierExtension, [Fhir.v6().Extension], default: [])
    field(:note, [Fhir.v6().Annotation], default: [])
    field(:oralDiet, Fhir.v6().NutritionOrderOralDiet)
    field(:orderer, Fhir.v6().Reference)
    field(:outsideFoodAllowed, :boolean)
    field(:performer, [Fhir.v6().CodeableReference], default: [])
    field(:priority, :string)
    field(:resourceType, :string, default: "NutritionOrder")
    field(:status, :string)
    field(:subject, Fhir.v6().Reference)
    field(:supplement, [Fhir.v6().NutritionOrderSupplement], default: [])
    field(:supportingInformation, [Fhir.v6().Reference], default: [])
    field(:text, Fhir.v6().Narrative)
  end
end
