defmodule Fhir.v6().Observation do
  use TypedStruct

  typedstruct do
    field(:_effectiveDateTime, Fhir.v6().Element)
    field(:_effectiveInstant, Fhir.v6().Element)
    field(:_implicitRules, Fhir.v6().Element)
    field(:_instantiatesCanonical, Fhir.v6().Element)
    field(:_issued, Fhir.v6().Element)
    field(:_language, Fhir.v6().Element)
    field(:_status, Fhir.v6().Element)
    field(:_valueBoolean, Fhir.v6().Element)
    field(:_valueDateTime, Fhir.v6().Element)
    field(:_valueInteger, Fhir.v6().Element)
    field(:_valueString, Fhir.v6().Element)
    field(:_valueTime, Fhir.v6().Element)
    field(:basedOn, [Fhir.v6().Reference], default: [])
    field(:bodySite, Fhir.v6().CodeableConcept)
    field(:bodyStructure, Fhir.v6().Reference)
    field(:category, [Fhir.v6().CodeableConcept], default: [])
    field(:code, Fhir.v6().CodeableConcept)
    field(:component, [Fhir.v6().ObservationComponent], default: [])
    field(:contained, [Fhir.v6().ResourceList], default: [])
    field(:dataAbsentReason, Fhir.v6().CodeableConcept)
    field(:derivedFrom, [Fhir.v6().Reference], default: [])
    field(:device, Fhir.v6().Reference)
    field(:effectiveDateTime, :string)
    field(:effectiveInstant, :string)
    field(:effectivePeriod, Fhir.v6().Period)
    field(:effectiveTiming, Fhir.v6().Timing)
    field(:encounter, Fhir.v6().Reference)
    field(:extension, [Fhir.v6().Extension], default: [])
    field(:focus, [Fhir.v6().Reference], default: [])
    field(:hasMember, [Fhir.v6().Reference], default: [])
    field(:id, :string)
    field(:identifier, [Fhir.v6().Identifier], default: [])
    field(:implicitRules, :string)
    field(:instantiatesCanonical, :string)
    field(:instantiatesReference, Fhir.v6().Reference)
    field(:interpretation, [Fhir.v6().CodeableConcept], default: [])
    field(:issued, :timestamp)
    field(:language, :string)
    field(:meta, Fhir.v6().Meta)
    field(:method, Fhir.v6().CodeableConcept)
    field(:modifierExtension, [Fhir.v6().Extension], default: [])
    field(:note, [Fhir.v6().Annotation], default: [])
    field(:partOf, [Fhir.v6().Reference], default: [])
    field(:performer, [Fhir.v6().Reference], default: [])
    field(:referenceRange, [Fhir.v6().ObservationReferenceRange], default: [])
    field(:resourceType, :string, default: "Observation")
    field(:specimen, Fhir.v6().Reference)
    field(:status, :string)
    field(:subject, Fhir.v6().Reference)
    field(:text, Fhir.v6().Narrative)
    field(:triggeredBy, [Fhir.v6().ObservationTriggeredBy], default: [])
    field(:valueAttachment, Fhir.v6().Attachment)
    field(:valueBoolean, :boolean)
    field(:valueCodeableConcept, Fhir.v6().CodeableConcept)
    field(:valueDateTime, :string)
    field(:valueInteger, :float)
    field(:valuePeriod, Fhir.v6().Period)
    field(:valueQuantity, Fhir.v6().Quantity)
    field(:valueRange, Fhir.v6().Range)
    field(:valueRatio, Fhir.v6().Ratio)
    field(:valueReference, Fhir.v6().Reference)
    field(:valueSampledData, Fhir.v6().SampledData)
    field(:valueString, :string)
    field(:valueTime, :string)
  end
end
