defmodule Fhir.v6().OperationDefinition do
  use TypedStruct

  typedstruct do
    field(:_affectsState, Fhir.v6().Element)
    field(:_code, Fhir.v6().Element)
    field(:_comment, Fhir.v6().Element)
    field(:_copyright, Fhir.v6().Element)
    field(:_copyrightLabel, Fhir.v6().Element)
    field(:_date, Fhir.v6().Element)
    field(:_description, Fhir.v6().Element)
    field(:_experimental, Fhir.v6().Element)
    field(:_implicitRules, Fhir.v6().Element)
    field(:_instance, Fhir.v6().Element)
    field(:_kind, Fhir.v6().Element)
    field(:_language, Fhir.v6().Element)
    field(:_name, Fhir.v6().Element)
    field(:_publisher, Fhir.v6().Element)
    field(:_purpose, Fhir.v6().Element)
    field(:_resource, [Fhir.v6().Element], default: [])
    field(:_status, Fhir.v6().Element)
    field(:_system, Fhir.v6().Element)
    field(:_title, Fhir.v6().Element)
    field(:_type, Fhir.v6().Element)
    field(:_url, Fhir.v6().Element)
    field(:_version, Fhir.v6().Element)
    field(:_versionAlgorithmString, Fhir.v6().Element)
    field(:affectsState, :boolean)
    field(:base, :string)
    field(:code, :string)
    field(:comment, :string)
    field(:contact, [Fhir.v6().ContactDetail], default: [])
    field(:contained, [Fhir.v6().ResourceList], default: [])
    field(:copyright, :string)
    field(:copyrightLabel, :string)
    field(:date, :datetime)
    field(:description, :string)
    field(:experimental, :boolean)
    field(:extension, [Fhir.v6().Extension], default: [])
    field(:id, :string)
    field(:identifier, [Fhir.v6().Identifier], default: [])
    field(:implicitRules, :string)
    field(:inputProfile, :string)
    field(:instance, :boolean)
    field(:jurisdiction, [Fhir.v6().CodeableConcept], default: [])
    field(:kind, :string)
    field(:language, :string)
    field(:meta, Fhir.v6().Meta)
    field(:modifierExtension, [Fhir.v6().Extension], default: [])
    field(:name, :string)
    field(:outputProfile, :string)
    field(:overload, [Fhir.v6().OperationDefinitionOverload], default: [])
    field(:parameter, [Fhir.v6().OperationDefinitionParameter], default: [])
    field(:publisher, :string)
    field(:purpose, :string)
    field(:resource, [:string], default: [])
    field(:resourceType, :string, default: "OperationDefinition")
    field(:status, :string)
    field(:system, :boolean)
    field(:text, Fhir.v6().Narrative)
    field(:title, :string)
    field(:type, :boolean)
    field(:url, :string)
    field(:useContext, [Fhir.v6().UsageContext], default: [])
    field(:version, :string)
    field(:versionAlgorithmCoding, Fhir.v6().Coding)
    field(:versionAlgorithmString, :string)
  end
end
