defmodule Fhir.v6().PaymentReconciliation do
  use TypedStruct

  typedstruct do
    field(:_accountNumber, Fhir.v6().Element)
    field(:_authorization, Fhir.v6().Element)
    field(:_cardBrand, Fhir.v6().Element)
    field(:_created, Fhir.v6().Element)
    field(:_date, Fhir.v6().Element)
    field(:_disposition, Fhir.v6().Element)
    field(:_expirationDate, Fhir.v6().Element)
    field(:_implicitRules, Fhir.v6().Element)
    field(:_language, Fhir.v6().Element)
    field(:_outcome, Fhir.v6().Element)
    field(:_processor, Fhir.v6().Element)
    field(:_referenceNumber, Fhir.v6().Element)
    field(:_status, Fhir.v6().Element)
    field(:accountNumber, :string)
    field(:allocation, [Fhir.v6().PaymentReconciliationAllocation], default: [])
    field(:amount, Fhir.v6().Money)
    field(:authorization, :string)
    field(:cardBrand, :string)
    field(:contained, [Fhir.v6().ResourceList], default: [])
    field(:created, :datetime)
    field(:date, :date)
    field(:disposition, :string)
    field(:enterer, Fhir.v6().Reference)
    field(:expirationDate, :date)
    field(:extension, [Fhir.v6().Extension], default: [])
    field(:formCode, Fhir.v6().CodeableConcept)
    field(:id, :string)
    field(:identifier, [Fhir.v6().Identifier], default: [])
    field(:implicitRules, :string)
    field(:issuerType, Fhir.v6().CodeableConcept)
    field(:kind, Fhir.v6().CodeableConcept)
    field(:language, :string)
    field(:location, Fhir.v6().Reference)
    field(:meta, Fhir.v6().Meta)
    field(:method, Fhir.v6().CodeableConcept)
    field(:modifierExtension, [Fhir.v6().Extension], default: [])
    field(:outcome, :string)
    field(:paymentIdentifier, Fhir.v6().Identifier)
    field(:paymentIssuer, Fhir.v6().Reference)
    field(:period, Fhir.v6().Period)
    field(:processNote, [Fhir.v6().PaymentReconciliationProcessNote], default: [])
    field(:processor, :string)
    field(:referenceNumber, :string)
    field(:request, Fhir.v6().Reference)
    field(:requestor, Fhir.v6().Reference)
    field(:resourceType, :string, default: "PaymentReconciliation")
    field(:returnedAmount, Fhir.v6().Money)
    field(:status, :string)
    field(:tenderedAmount, Fhir.v6().Money)
    field(:text, Fhir.v6().Narrative)
    field(:type, Fhir.v6().CodeableConcept)
  end
end
