defmodule Fhir.v6().PlanDefinitionAction do
  use TypedStruct

  typedstruct do
    field(:_cardinalityBehavior, Fhir.v6().Element)
    field(:_definitionCanonical, Fhir.v6().Element)
    field(:_definitionUri, Fhir.v6().Element)
    field(:_description, Fhir.v6().Element)
    field(:_goalId, [Fhir.v6().Element], default: [])
    field(:_groupingBehavior, Fhir.v6().Element)
    field(:_linkId, Fhir.v6().Element)
    field(:_precheckBehavior, Fhir.v6().Element)
    field(:_prefix, Fhir.v6().Element)
    field(:_priority, Fhir.v6().Element)
    field(:_requiredBehavior, Fhir.v6().Element)
    field(:_selectionBehavior, Fhir.v6().Element)
    field(:_subjectCanonical, Fhir.v6().Element)
    field(:_textEquivalent, Fhir.v6().Element)
    field(:_title, Fhir.v6().Element)
    field(:action, [Fhir.v6().PlanDefinitionAction], default: [])
    field(:cardinalityBehavior, :string)
    field(:code, Fhir.v6().CodeableConcept)
    field(:condition, [Fhir.v6().PlanDefinitionCondition], default: [])
    field(:definitionCanonical, :string)
    field(:definitionUri, :string)
    field(:description, :string)
    field(:documentation, [Fhir.v6().RelatedArtifact], default: [])
    field(:dynamicValue, [Fhir.v6().PlanDefinitionDynamicValue], default: [])
    field(:extension, [Fhir.v6().Extension], default: [])
    field(:goalId, [:string], default: [])
    field(:groupingBehavior, :string)
    field(:id, :string)
    field(:input, [Fhir.v6().PlanDefinitionInput], default: [])
    field(:linkId, :string)
    field(:location, Fhir.v6().CodeableReference)
    field(:modifierExtension, [Fhir.v6().Extension], default: [])
    field(:output, [Fhir.v6().PlanDefinitionOutput], default: [])
    field(:participant, [Fhir.v6().PlanDefinitionParticipant], default: [])
    field(:precheckBehavior, :string)
    field(:prefix, :string)
    field(:priority, :string)
    field(:reason, [Fhir.v6().CodeableConcept], default: [])
    field(:relatedAction, [Fhir.v6().PlanDefinitionRelatedAction], default: [])
    field(:requiredBehavior, :string)
    field(:selectionBehavior, :string)
    field(:subjectCanonical, :string)
    field(:subjectCodeableConcept, Fhir.v6().CodeableConcept)
    field(:subjectReference, Fhir.v6().Reference)
    field(:textEquivalent, :string)
    field(:timingAge, Fhir.v6().Age)
    field(:timingDuration, Fhir.v6().Duration)
    field(:timingRange, Fhir.v6().Range)
    field(:timingTiming, Fhir.v6().Timing)
    field(:title, :string)
    field(:transform, :string)
    field(:trigger, [Fhir.v6().TriggerDefinition], default: [])
    field(:type, Fhir.v6().CodeableConcept)
  end
end
