defmodule Fhir.v6().Procedure do
  use TypedStruct

  typedstruct do
    field(:_implicitRules, Fhir.v6().Element)
    field(:_instantiatesUri, [Fhir.v6().Element], default: [])
    field(:_language, Fhir.v6().Element)
    field(:_occurrenceDateTime, Fhir.v6().Element)
    field(:_occurrenceString, Fhir.v6().Element)
    field(:_recorded, Fhir.v6().Element)
    field(:_reportedBoolean, Fhir.v6().Element)
    field(:_status, Fhir.v6().Element)
    field(:basedOn, [Fhir.v6().Reference], default: [])
    field(:bodySite, [Fhir.v6().CodeableConcept], default: [])
    field(:category, [Fhir.v6().CodeableConcept], default: [])
    field(:code, Fhir.v6().CodeableConcept)
    field(:complication, [Fhir.v6().CodeableReference], default: [])
    field(:contained, [Fhir.v6().ResourceList], default: [])
    field(:encounter, Fhir.v6().Reference)
    field(:extension, [Fhir.v6().Extension], default: [])
    field(:focalDevice, [Fhir.v6().ProcedureFocalDevice], default: [])
    field(:focus, Fhir.v6().Reference)
    field(:followUp, [Fhir.v6().CodeableConcept], default: [])
    field(:id, :string)
    field(:identifier, [Fhir.v6().Identifier], default: [])
    field(:implicitRules, :string)
    field(:instantiatesCanonical, [:string], default: [])
    field(:instantiatesUri, [:string], default: [])
    field(:language, :string)
    field(:location, Fhir.v6().Reference)
    field(:meta, Fhir.v6().Meta)
    field(:modifierExtension, [Fhir.v6().Extension], default: [])
    field(:note, [Fhir.v6().Annotation], default: [])
    field(:occurrenceAge, Fhir.v6().Age)
    field(:occurrenceDateTime, :string)
    field(:occurrencePeriod, Fhir.v6().Period)
    field(:occurrenceRange, Fhir.v6().Range)
    field(:occurrenceString, :string)
    field(:occurrenceTiming, Fhir.v6().Timing)
    field(:outcome, Fhir.v6().CodeableConcept)
    field(:partOf, [Fhir.v6().Reference], default: [])
    field(:performer, [Fhir.v6().ProcedurePerformer], default: [])
    field(:reason, [Fhir.v6().CodeableReference], default: [])
    field(:recorded, :datetime)
    field(:recorder, Fhir.v6().Reference)
    field(:report, [Fhir.v6().Reference], default: [])
    field(:reportedBoolean, :boolean)
    field(:reportedReference, Fhir.v6().Reference)
    field(:resourceType, :string, default: "Procedure")
    field(:status, :string)
    field(:statusReason, Fhir.v6().CodeableConcept)
    field(:subject, Fhir.v6().Reference)
    field(:supportingInfo, [Fhir.v6().Reference], default: [])
    field(:text, Fhir.v6().Narrative)
    field(:used, [Fhir.v6().CodeableReference], default: [])
  end
end
