defmodule Fhir.v6().QuestionnaireItem do
  use TypedStruct

  typedstruct do
    field(:_answerConstraint, Fhir.v6().Element)
    field(:_definition, Fhir.v6().Element)
    field(:_disabledDisplay, Fhir.v6().Element)
    field(:_enableBehavior, Fhir.v6().Element)
    field(:_linkId, Fhir.v6().Element)
    field(:_maxLength, Fhir.v6().Element)
    field(:_prefix, Fhir.v6().Element)
    field(:_readOnly, Fhir.v6().Element)
    field(:_repeats, Fhir.v6().Element)
    field(:_required, Fhir.v6().Element)
    field(:_text, Fhir.v6().Element)
    field(:_type, Fhir.v6().Element)
    field(:answerConstraint, :string)
    field(:answerOption, [Fhir.v6().QuestionnaireAnswerOption], default: [])
    field(:answerValueSet, :string)
    field(:code, [Fhir.v6().Coding], default: [])
    field(:definition, :string)
    field(:disabledDisplay, :string)
    field(:enableBehavior, :string)
    field(:enableWhen, [Fhir.v6().QuestionnaireEnableWhen], default: [])
    field(:extension, [Fhir.v6().Extension], default: [])
    field(:id, :string)
    field(:initial, [Fhir.v6().QuestionnaireInitial], default: [])
    field(:item, [Fhir.v6().QuestionnaireItem], default: [])
    field(:linkId, :string)
    field(:maxLength, :float)
    field(:modifierExtension, [Fhir.v6().Extension], default: [])
    field(:prefix, :string)
    field(:readOnly, :boolean)
    field(:repeats, :boolean)
    field(:required, :boolean)
    field(:text, :string)
    field(:type, :string)
  end
end
