defmodule Fhir.v6().RequestOrchestrationAction do
  use TypedStruct

  typedstruct do
    field(:_cardinalityBehavior, Fhir.v6().Element)
    field(:_definitionCanonical, Fhir.v6().Element)
    field(:_definitionUri, Fhir.v6().Element)
    field(:_description, Fhir.v6().Element)
    field(:_groupingBehavior, Fhir.v6().Element)
    field(:_linkId, Fhir.v6().Element)
    field(:_precheckBehavior, Fhir.v6().Element)
    field(:_prefix, Fhir.v6().Element)
    field(:_priority, Fhir.v6().Element)
    field(:_requiredBehavior, Fhir.v6().Element)
    field(:_selectionBehavior, Fhir.v6().Element)
    field(:_textEquivalent, Fhir.v6().Element)
    field(:_timingDateTime, Fhir.v6().Element)
    field(:_title, Fhir.v6().Element)
    field(:action, [Fhir.v6().RequestOrchestrationAction], default: [])
    field(:cardinalityBehavior, :string)
    field(:code, [Fhir.v6().CodeableConcept], default: [])
    field(:condition, [Fhir.v6().RequestOrchestrationCondition], default: [])
    field(:definitionCanonical, :string)
    field(:definitionUri, :string)
    field(:description, :string)
    field(:documentation, [Fhir.v6().RelatedArtifact], default: [])
    field(:dynamicValue, [Fhir.v6().RequestOrchestrationDynamicValue], default: [])
    field(:extension, [Fhir.v6().Extension], default: [])
    field(:goal, [Fhir.v6().Reference], default: [])
    field(:groupingBehavior, :string)
    field(:id, :string)
    field(:input, [Fhir.v6().RequestOrchestrationInput], default: [])
    field(:linkId, :string)
    field(:location, Fhir.v6().CodeableReference)
    field(:modifierExtension, [Fhir.v6().Extension], default: [])
    field(:output, [Fhir.v6().RequestOrchestrationOutput], default: [])
    field(:participant, [Fhir.v6().RequestOrchestrationParticipant], default: [])
    field(:precheckBehavior, :string)
    field(:prefix, :string)
    field(:priority, :string)
    field(:relatedAction, [Fhir.v6().RequestOrchestrationRelatedAction], default: [])
    field(:requiredBehavior, :string)
    field(:resource, Fhir.v6().Reference)
    field(:selectionBehavior, :string)
    field(:textEquivalent, :string)
    field(:timingAge, Fhir.v6().Age)
    field(:timingDateTime, :string)
    field(:timingDuration, Fhir.v6().Duration)
    field(:timingPeriod, Fhir.v6().Period)
    field(:timingRange, Fhir.v6().Range)
    field(:timingTiming, Fhir.v6().Timing)
    field(:title, :string)
    field(:transform, :string)
    field(:type, Fhir.v6().CodeableConcept)
  end
end
