defmodule Fhir.v6().RequestOrchestration do
  use TypedStruct

  typedstruct do
    field(:_authoredOn, Fhir.v6().Element)
    field(:_implicitRules, Fhir.v6().Element)
    field(:_instantiatesCanonical, [Fhir.v6().Element], default: [])
    field(:_instantiatesUri, [Fhir.v6().Element], default: [])
    field(:_intent, Fhir.v6().Element)
    field(:_language, Fhir.v6().Element)
    field(:_priority, Fhir.v6().Element)
    field(:_status, Fhir.v6().Element)
    field(:action, [Fhir.v6().RequestOrchestrationAction], default: [])
    field(:author, Fhir.v6().Reference)
    field(:authoredOn, :datetime)
    field(:basedOn, [Fhir.v6().Reference], default: [])
    field(:code, Fhir.v6().CodeableConcept)
    field(:contained, [Fhir.v6().ResourceList], default: [])
    field(:encounter, Fhir.v6().Reference)
    field(:extension, [Fhir.v6().Extension], default: [])
    field(:goal, [Fhir.v6().Reference], default: [])
    field(:groupIdentifier, Fhir.v6().Identifier)
    field(:id, :string)
    field(:identifier, [Fhir.v6().Identifier], default: [])
    field(:implicitRules, :string)
    field(:instantiatesCanonical, [:string], default: [])
    field(:instantiatesUri, [:string], default: [])
    field(:intent, :string)
    field(:language, :string)
    field(:meta, Fhir.v6().Meta)
    field(:modifierExtension, [Fhir.v6().Extension], default: [])
    field(:note, [Fhir.v6().Annotation], default: [])
    field(:priority, :string)
    field(:reason, [Fhir.v6().CodeableReference], default: [])
    field(:replaces, [Fhir.v6().Reference], default: [])
    field(:resourceType, :string, default: "RequestOrchestration")
    field(:status, :string)
    field(:subject, Fhir.v6().Reference)
    field(:text, Fhir.v6().Narrative)
  end
end
