defmodule Fhir.v6().ResearchStudy do
  use TypedStruct

  typedstruct do
    field(:_date, Fhir.v6().Element)
    field(:_description, Fhir.v6().Element)
    field(:_descriptionSummary, Fhir.v6().Element)
    field(:_implicitRules, Fhir.v6().Element)
    field(:_language, Fhir.v6().Element)
    field(:_name, Fhir.v6().Element)
    field(:_status, Fhir.v6().Element)
    field(:_title, Fhir.v6().Element)
    field(:_url, Fhir.v6().Element)
    field(:_version, Fhir.v6().Element)
    field(:associatedParty, [Fhir.v6().ResearchStudyAssociatedParty], default: [])
    field(:classifier, [Fhir.v6().CodeableConcept], default: [])
    field(:comparisonGroup, [Fhir.v6().ResearchStudyComparisonGroup], default: [])
    field(:condition, [Fhir.v6().CodeableConcept], default: [])
    field(:contained, [Fhir.v6().ResourceList], default: [])
    field(:date, :datetime)
    field(:description, :string)
    field(:descriptionSummary, :string)
    field(:extension, [Fhir.v6().Extension], default: [])
    field(:focus, [Fhir.v6().CodeableReference], default: [])
    field(:id, :string)
    field(:identifier, [Fhir.v6().Identifier], default: [])
    field(:implicitRules, :string)
    field(:keyword, [Fhir.v6().CodeableConcept], default: [])
    field(:label, [Fhir.v6().ResearchStudyLabel], default: [])
    field(:language, :string)
    field(:meta, Fhir.v6().Meta)
    field(:modifierExtension, [Fhir.v6().Extension], default: [])
    field(:name, :string)
    field(:note, [Fhir.v6().Annotation], default: [])
    field(:objective, [Fhir.v6().ResearchStudyObjective], default: [])
    field(:outcomeMeasure, [Fhir.v6().ResearchStudyOutcomeMeasure], default: [])
    field(:partOf, [Fhir.v6().Reference], default: [])
    field(:period, Fhir.v6().Period)
    field(:phase, Fhir.v6().CodeableConcept)
    field(:primaryPurposeType, Fhir.v6().CodeableConcept)
    field(:progressStatus, [Fhir.v6().ResearchStudyProgressStatus], default: [])
    field(:protocol, [Fhir.v6().Reference], default: [])
    field(:recruitment, Fhir.v6().ResearchStudyRecruitment)
    field(:region, [Fhir.v6().CodeableConcept], default: [])
    field(:relatedArtifact, [Fhir.v6().RelatedArtifact], default: [])
    field(:resourceType, :string, default: "ResearchStudy")
    field(:result, [Fhir.v6().Reference], default: [])
    field(:site, [Fhir.v6().Reference], default: [])
    field(:status, :string)
    field(:studyDesign, [Fhir.v6().CodeableConcept], default: [])
    field(:text, Fhir.v6().Narrative)
    field(:title, :string)
    field(:url, :string)
    field(:version, :string)
    field(:whyStopped, Fhir.v6().CodeableConcept)
  end
end
