defmodule Fhir.v6().SearchParameter do
  use TypedStruct

  typedstruct do
    field(:_base, [Fhir.v6().Element], default: [])
    field(:_chain, [Fhir.v6().Element], default: [])
    field(:_code, Fhir.v6().Element)
    field(:_comparator, [Fhir.v6().Element], default: [])
    field(:_constraint, Fhir.v6().Element)
    field(:_copyright, Fhir.v6().Element)
    field(:_copyrightLabel, Fhir.v6().Element)
    field(:_date, Fhir.v6().Element)
    field(:_description, Fhir.v6().Element)
    field(:_experimental, Fhir.v6().Element)
    field(:_expression, Fhir.v6().Element)
    field(:_implicitRules, Fhir.v6().Element)
    field(:_language, Fhir.v6().Element)
    field(:_modifier, [Fhir.v6().Element], default: [])
    field(:_multipleAnd, Fhir.v6().Element)
    field(:_multipleOr, Fhir.v6().Element)
    field(:_name, Fhir.v6().Element)
    field(:_processingMode, Fhir.v6().Element)
    field(:_publisher, Fhir.v6().Element)
    field(:_purpose, Fhir.v6().Element)
    field(:_status, Fhir.v6().Element)
    field(:_target, [Fhir.v6().Element], default: [])
    field(:_title, Fhir.v6().Element)
    field(:_type, Fhir.v6().Element)
    field(:_url, Fhir.v6().Element)
    field(:_version, Fhir.v6().Element)
    field(:_versionAlgorithmString, Fhir.v6().Element)
    field(:base, [:string], default: [])
    field(:chain, [:string], default: [])
    field(:code, :string)
    field(:comparator, [:string], default: [])
    field(:component, [Fhir.v6().SearchParameterComponent], default: [])
    field(:constraint, :string)
    field(:contact, [Fhir.v6().ContactDetail], default: [])
    field(:contained, [Fhir.v6().ResourceList], default: [])
    field(:copyright, :string)
    field(:copyrightLabel, :string)
    field(:date, :datetime)
    field(:derivedFrom, :string)
    field(:description, :string)
    field(:experimental, :boolean)
    field(:expression, :string)
    field(:extension, [Fhir.v6().Extension], default: [])
    field(:id, :string)
    field(:identifier, [Fhir.v6().Identifier], default: [])
    field(:implicitRules, :string)
    field(:jurisdiction, [Fhir.v6().CodeableConcept], default: [])
    field(:language, :string)
    field(:meta, Fhir.v6().Meta)
    field(:modifier, [:string], default: [])
    field(:modifierExtension, [Fhir.v6().Extension], default: [])
    field(:multipleAnd, :boolean)
    field(:multipleOr, :boolean)
    field(:name, :string)
    field(:processingMode, :string)
    field(:publisher, :string)
    field(:purpose, :string)
    field(:resourceType, :string, default: "SearchParameter")
    field(:status, :string)
    field(:target, [:string], default: [])
    field(:text, Fhir.v6().Narrative)
    field(:title, :string)
    field(:type, :string)
    field(:url, :string)
    field(:useContext, [Fhir.v6().UsageContext], default: [])
    field(:version, :string)
    field(:versionAlgorithmCoding, Fhir.v6().Coding)
    field(:versionAlgorithmString, :string)
  end
end
