defmodule Fhir.v6().ServiceRequest do
  use TypedStruct

  typedstruct do
    field(:_asNeededBoolean, Fhir.v6().Element)
    field(:_authoredOn, Fhir.v6().Element)
    field(:_doNotPerform, Fhir.v6().Element)
    field(:_implicitRules, Fhir.v6().Element)
    field(:_instantiatesUri, [Fhir.v6().Element], default: [])
    field(:_intent, Fhir.v6().Element)
    field(:_language, Fhir.v6().Element)
    field(:_occurrenceDateTime, Fhir.v6().Element)
    field(:_priority, Fhir.v6().Element)
    field(:_status, Fhir.v6().Element)
    field(:asNeededBoolean, :boolean)
    field(:asNeededCodeableConcept, Fhir.v6().CodeableConcept)
    field(:authoredOn, :datetime)
    field(:basedOn, [Fhir.v6().Reference], default: [])
    field(:bodySite, [Fhir.v6().CodeableConcept], default: [])
    field(:bodyStructure, Fhir.v6().Reference)
    field(:category, [Fhir.v6().CodeableConcept], default: [])
    field(:code, Fhir.v6().CodeableReference)
    field(:contained, [Fhir.v6().ResourceList], default: [])
    field(:doNotPerform, :boolean)
    field(:encounter, Fhir.v6().Reference)
    field(:extension, [Fhir.v6().Extension], default: [])
    field(:focus, [Fhir.v6().Reference], default: [])
    field(:id, :string)
    field(:identifier, [Fhir.v6().Identifier], default: [])
    field(:implicitRules, :string)
    field(:instantiatesCanonical, [:string], default: [])
    field(:instantiatesUri, [:string], default: [])
    field(:insurance, [Fhir.v6().Reference], default: [])
    field(:intent, :string)
    field(:language, :string)
    field(:location, [Fhir.v6().CodeableReference], default: [])
    field(:meta, Fhir.v6().Meta)
    field(:modifierExtension, [Fhir.v6().Extension], default: [])
    field(:note, [Fhir.v6().Annotation], default: [])
    field(:occurrenceDateTime, :string)
    field(:occurrencePeriod, Fhir.v6().Period)
    field(:occurrenceTiming, Fhir.v6().Timing)
    field(:orderDetail, [Fhir.v6().ServiceRequestOrderDetail], default: [])
    field(:patientInstruction, [Fhir.v6().ServiceRequestPatientInstruction], default: [])
    field(:performer, [Fhir.v6().Reference], default: [])
    field(:performerType, Fhir.v6().CodeableConcept)
    field(:priority, :string)
    field(:quantityQuantity, Fhir.v6().Quantity)
    field(:quantityRange, Fhir.v6().Range)
    field(:quantityRatio, Fhir.v6().Ratio)
    field(:reason, [Fhir.v6().CodeableReference], default: [])
    field(:relevantHistory, [Fhir.v6().Reference], default: [])
    field(:replaces, [Fhir.v6().Reference], default: [])
    field(:requester, Fhir.v6().Reference)
    field(:requisition, Fhir.v6().Identifier)
    field(:resourceType, :string, default: "ServiceRequest")
    field(:specimen, [Fhir.v6().Reference], default: [])
    field(:status, :string)
    field(:subject, Fhir.v6().Reference)
    field(:supportingInfo, [Fhir.v6().CodeableReference], default: [])
    field(:text, Fhir.v6().Narrative)
  end
end
