defmodule Fhir.v6().Specimen do
  use TypedStruct

  typedstruct do
    field(:_combined, Fhir.v6().Element)
    field(:_implicitRules, Fhir.v6().Element)
    field(:_language, Fhir.v6().Element)
    field(:_receivedTime, Fhir.v6().Element)
    field(:_status, Fhir.v6().Element)
    field(:accessionIdentifier, Fhir.v6().Identifier)
    field(:collection, Fhir.v6().SpecimenCollection)
    field(:combined, :string)
    field(:condition, [Fhir.v6().CodeableConcept], default: [])
    field(:contained, [Fhir.v6().ResourceList], default: [])
    field(:container, [Fhir.v6().SpecimenContainer], default: [])
    field(:extension, [Fhir.v6().Extension], default: [])
    field(:feature, [Fhir.v6().SpecimenFeature], default: [])
    field(:id, :string)
    field(:identifier, [Fhir.v6().Identifier], default: [])
    field(:implicitRules, :string)
    field(:language, :string)
    field(:meta, Fhir.v6().Meta)
    field(:modifierExtension, [Fhir.v6().Extension], default: [])
    field(:note, [Fhir.v6().Annotation], default: [])
    field(:parent, [Fhir.v6().Reference], default: [])
    field(:processing, [Fhir.v6().SpecimenProcessing], default: [])
    field(:receivedTime, :datetime)
    field(:request, [Fhir.v6().Reference], default: [])
    field(:resourceType, :string, default: "Specimen")
    field(:role, [Fhir.v6().CodeableConcept], default: [])
    field(:status, :string)
    field(:subject, Fhir.v6().Reference)
    field(:text, Fhir.v6().Narrative)
    field(:type, Fhir.v6().CodeableConcept)
  end
end
