defmodule Fhir.v6().StructureDefinition do
  use TypedStruct

  typedstruct do
    field(:_abstract, Fhir.v6().Element)
    field(:_contextInvariant, [Fhir.v6().Element], default: [])
    field(:_copyright, Fhir.v6().Element)
    field(:_copyrightLabel, Fhir.v6().Element)
    field(:_date, Fhir.v6().Element)
    field(:_derivation, Fhir.v6().Element)
    field(:_description, Fhir.v6().Element)
    field(:_experimental, Fhir.v6().Element)
    field(:_fhirVersion, Fhir.v6().Element)
    field(:_implicitRules, Fhir.v6().Element)
    field(:_kind, Fhir.v6().Element)
    field(:_language, Fhir.v6().Element)
    field(:_name, Fhir.v6().Element)
    field(:_publisher, Fhir.v6().Element)
    field(:_purpose, Fhir.v6().Element)
    field(:_status, Fhir.v6().Element)
    field(:_title, Fhir.v6().Element)
    field(:_type, Fhir.v6().Element)
    field(:_url, Fhir.v6().Element)
    field(:_version, Fhir.v6().Element)
    field(:_versionAlgorithmString, Fhir.v6().Element)
    field(:abstract, :boolean)
    field(:baseDefinition, :string)
    field(:contact, [Fhir.v6().ContactDetail], default: [])
    field(:contained, [Fhir.v6().ResourceList], default: [])
    field(:context, [Fhir.v6().StructureDefinitionContext], default: [])
    field(:contextInvariant, [:string], default: [])
    field(:copyright, :string)
    field(:copyrightLabel, :string)
    field(:date, :datetime)
    field(:derivation, :string)
    field(:description, :string)
    field(:differential, Fhir.v6().StructureDefinitionDifferential)
    field(:experimental, :boolean)
    field(:extension, [Fhir.v6().Extension], default: [])
    field(:fhirVersion, :string)
    field(:id, :string)
    field(:identifier, [Fhir.v6().Identifier], default: [])
    field(:implicitRules, :string)
    field(:jurisdiction, [Fhir.v6().CodeableConcept], default: [])
    field(:keyword, [Fhir.v6().Coding], default: [])
    field(:kind, :string)
    field(:language, :string)
    field(:mapping, [Fhir.v6().StructureDefinitionMapping], default: [])
    field(:meta, Fhir.v6().Meta)
    field(:modifierExtension, [Fhir.v6().Extension], default: [])
    field(:name, :string)
    field(:publisher, :string)
    field(:purpose, :string)
    field(:resourceType, :string, default: "StructureDefinition")
    field(:snapshot, Fhir.v6().StructureDefinitionSnapshot)
    field(:status, :string)
    field(:text, Fhir.v6().Narrative)
    field(:title, :string)
    field(:type, :string)
    field(:url, :string)
    field(:useContext, [Fhir.v6().UsageContext], default: [])
    field(:version, :string)
    field(:versionAlgorithmCoding, Fhir.v6().Coding)
    field(:versionAlgorithmString, :string)
  end
end
