defmodule Fhir.v6().SubstanceDefinition do
  use TypedStruct

  typedstruct do
    field(:_description, Fhir.v6().Element)
    field(:_implicitRules, Fhir.v6().Element)
    field(:_language, Fhir.v6().Element)
    field(:_version, Fhir.v6().Element)
    field(:characterization, [Fhir.v6().SubstanceDefinitionCharacterization], default: [])
    field(:classification, [Fhir.v6().CodeableConcept], default: [])
    field(:code, [Fhir.v6().SubstanceDefinitionCode], default: [])
    field(:contained, [Fhir.v6().ResourceList], default: [])
    field(:description, :string)
    field(:domain, Fhir.v6().CodeableConcept)
    field(:extension, [Fhir.v6().Extension], default: [])
    field(:grade, [Fhir.v6().CodeableConcept], default: [])
    field(:id, :string)
    field(:identifier, [Fhir.v6().Identifier], default: [])
    field(:implicitRules, :string)
    field(:informationSource, [Fhir.v6().Reference], default: [])
    field(:language, :string)
    field(:manufacturer, [Fhir.v6().Reference], default: [])
    field(:meta, Fhir.v6().Meta)
    field(:modifierExtension, [Fhir.v6().Extension], default: [])
    field(:moiety, [Fhir.v6().SubstanceDefinitionMoiety], default: [])
    field(:molecularWeight, [Fhir.v6().SubstanceDefinitionMolecularWeight], default: [])
    field(:name, [Fhir.v6().SubstanceDefinitionName], default: [])
    field(:note, [Fhir.v6().Annotation], default: [])
    field(:nucleicAcid, Fhir.v6().Reference)
    field(:polymer, Fhir.v6().Reference)
    field(:property, [Fhir.v6().SubstanceDefinitionProperty], default: [])
    field(:protein, Fhir.v6().Reference)
    field(:referenceInformation, Fhir.v6().Reference)
    field(:relationship, [Fhir.v6().SubstanceDefinitionRelationship], default: [])
    field(:resourceType, :string, default: "SubstanceDefinition")
    field(:sourceMaterial, Fhir.v6().SubstanceDefinitionSourceMaterial)
    field(:status, Fhir.v6().CodeableConcept)
    field(:structure, Fhir.v6().SubstanceDefinitionStructure)
    field(:supplier, [Fhir.v6().Reference], default: [])
    field(:text, Fhir.v6().Narrative)
    field(:version, :string)
  end
end
