defmodule Fhir.v6().Subscription do
  use TypedStruct

  typedstruct do
    field(:_content, Fhir.v6().Element)
    field(:_contentType, Fhir.v6().Element)
    field(:_end, Fhir.v6().Element)
    field(:_endpoint, Fhir.v6().Element)
    field(:_heartbeatPeriod, Fhir.v6().Element)
    field(:_implicitRules, Fhir.v6().Element)
    field(:_language, Fhir.v6().Element)
    field(:_maxCount, Fhir.v6().Element)
    field(:_name, Fhir.v6().Element)
    field(:_reason, Fhir.v6().Element)
    field(:_status, Fhir.v6().Element)
    field(:_timeout, Fhir.v6().Element)
    field(:channelType, Fhir.v6().Coding)
    field(:contact, [Fhir.v6().ContactPoint], default: [])
    field(:contained, [Fhir.v6().ResourceList], default: [])
    field(:content, :string)
    field(:contentType, :string)
    field(:end, :timestamp)
    field(:endpoint, :string)
    field(:extension, [Fhir.v6().Extension], default: [])
    field(:filterBy, [Fhir.v6().SubscriptionFilterBy], default: [])
    field(:heartbeatPeriod, :float)
    field(:id, :string)
    field(:identifier, [Fhir.v6().Identifier], default: [])
    field(:implicitRules, :string)
    field(:language, :string)
    field(:managingEntity, Fhir.v6().Reference)
    field(:maxCount, :float)
    field(:meta, Fhir.v6().Meta)
    field(:modifierExtension, [Fhir.v6().Extension], default: [])
    field(:name, :string)
    field(:parameter, [Fhir.v6().SubscriptionParameter], default: [])
    field(:reason, :string)
    field(:resourceType, :string, default: "Subscription")
    field(:status, :string)
    field(:text, Fhir.v6().Narrative)
    field(:timeout, :float)
    field(:topic, :string)
  end
end
