defmodule Fhir.v6().SupplyRequest do
  use TypedStruct

  typedstruct do
    field(:_authoredOn, Fhir.v6().Element)
    field(:_implicitRules, Fhir.v6().Element)
    field(:_language, Fhir.v6().Element)
    field(:_occurrenceDateTime, Fhir.v6().Element)
    field(:_priority, Fhir.v6().Element)
    field(:_status, Fhir.v6().Element)
    field(:authoredOn, :datetime)
    field(:basedOn, [Fhir.v6().Reference], default: [])
    field(:category, Fhir.v6().CodeableConcept)
    field(:contained, [Fhir.v6().ResourceList], default: [])
    field(:deliverFor, Fhir.v6().Reference)
    field(:deliverFrom, Fhir.v6().Reference)
    field(:deliverTo, Fhir.v6().Reference)
    field(:extension, [Fhir.v6().Extension], default: [])
    field(:id, :string)
    field(:identifier, [Fhir.v6().Identifier], default: [])
    field(:implicitRules, :string)
    field(:item, Fhir.v6().CodeableReference)
    field(:language, :string)
    field(:meta, Fhir.v6().Meta)
    field(:modifierExtension, [Fhir.v6().Extension], default: [])
    field(:occurrenceDateTime, :string)
    field(:occurrencePeriod, Fhir.v6().Period)
    field(:occurrenceTiming, Fhir.v6().Timing)
    field(:parameter, [Fhir.v6().SupplyRequestParameter], default: [])
    field(:priority, :string)
    field(:quantity, Fhir.v6().Quantity)
    field(:reason, [Fhir.v6().CodeableReference], default: [])
    field(:requester, Fhir.v6().Reference)
    field(:resourceType, :string, default: "SupplyRequest")
    field(:status, :string)
    field(:supplier, [Fhir.v6().Reference], default: [])
    field(:text, Fhir.v6().Narrative)
  end
end
