defmodule Fhir.v6().Task do
  use TypedStruct

  typedstruct do
    field(:_authoredOn, Fhir.v6().Element)
    field(:_description, Fhir.v6().Element)
    field(:_doNotPerform, Fhir.v6().Element)
    field(:_implicitRules, Fhir.v6().Element)
    field(:_instantiatesUri, Fhir.v6().Element)
    field(:_intent, Fhir.v6().Element)
    field(:_language, Fhir.v6().Element)
    field(:_lastModified, Fhir.v6().Element)
    field(:_priority, Fhir.v6().Element)
    field(:_status, Fhir.v6().Element)
    field(:authoredOn, :datetime)
    field(:basedOn, [Fhir.v6().Reference], default: [])
    field(:businessStatus, Fhir.v6().CodeableConcept)
    field(:code, Fhir.v6().CodeableConcept)
    field(:contained, [Fhir.v6().ResourceList], default: [])
    field(:description, :string)
    field(:doNotPerform, :boolean)
    field(:encounter, Fhir.v6().Reference)
    field(:executionPeriod, Fhir.v6().Period)
    field(:extension, [Fhir.v6().Extension], default: [])
    field(:focus, Fhir.v6().Reference)
    field(:for, Fhir.v6().Reference)
    field(:groupIdentifier, Fhir.v6().Identifier)
    field(:id, :string)
    field(:identifier, [Fhir.v6().Identifier], default: [])
    field(:implicitRules, :string)
    field(:input, [Fhir.v6().TaskInput], default: [])
    field(:instantiatesCanonical, :string)
    field(:instantiatesUri, :string)
    field(:insurance, [Fhir.v6().Reference], default: [])
    field(:intent, :string)
    field(:language, :string)
    field(:lastModified, :datetime)
    field(:location, Fhir.v6().Reference)
    field(:meta, Fhir.v6().Meta)
    field(:modifierExtension, [Fhir.v6().Extension], default: [])
    field(:note, [Fhir.v6().Annotation], default: [])
    field(:output, [Fhir.v6().TaskOutput], default: [])
    field(:owner, Fhir.v6().Reference)
    field(:partOf, [Fhir.v6().Reference], default: [])
    field(:performer, [Fhir.v6().TaskPerformer], default: [])
    field(:priority, :string)
    field(:reason, [Fhir.v6().CodeableReference], default: [])
    field(:relevantHistory, [Fhir.v6().Reference], default: [])
    field(:requestedPerformer, [Fhir.v6().CodeableReference], default: [])
    field(:requestedPeriod, Fhir.v6().Period)
    field(:requester, Fhir.v6().Reference)
    field(:resourceType, :string, default: "Task")
    field(:restriction, Fhir.v6().TaskRestriction)
    field(:status, :string)
    field(:statusReason, Fhir.v6().CodeableReference)
    field(:text, Fhir.v6().Narrative)
  end
end
