defmodule Fhir.v6().TestScriptOperation do
  use TypedStruct

  typedstruct do
    field(:_accept, Fhir.v6().Element)
    field(:_contentType, Fhir.v6().Element)
    field(:_description, Fhir.v6().Element)
    field(:_destination, Fhir.v6().Element)
    field(:_encodeRequestUrl, Fhir.v6().Element)
    field(:_label, Fhir.v6().Element)
    field(:_method, Fhir.v6().Element)
    field(:_origin, Fhir.v6().Element)
    field(:_params, Fhir.v6().Element)
    field(:_requestId, Fhir.v6().Element)
    field(:_resource, Fhir.v6().Element)
    field(:_responseId, Fhir.v6().Element)
    field(:_sourceId, Fhir.v6().Element)
    field(:_targetId, Fhir.v6().Element)
    field(:_url, Fhir.v6().Element)
    field(:accept, :string)
    field(:contentType, :string)
    field(:description, :string)
    field(:destination, :float)
    field(:encodeRequestUrl, :boolean)
    field(:extension, [Fhir.v6().Extension], default: [])
    field(:id, :string)
    field(:label, :string)
    field(:method, :string)
    field(:modifierExtension, [Fhir.v6().Extension], default: [])
    field(:origin, :float)
    field(:params, :string)
    field(:requestHeader, [Fhir.v6().TestScriptRequestHeader], default: [])
    field(:requestId, :string)
    field(:resource, :string)
    field(:responseId, :string)
    field(:sourceId, :string)
    field(:targetId, :string)
    field(:type, Fhir.v6().Coding)
    field(:url, :string)
  end
end
