defmodule Fhir.v6().TestScript do
  use TypedStruct

  typedstruct do
    field(:_copyright, Fhir.v6().Element)
    field(:_copyrightLabel, Fhir.v6().Element)
    field(:_date, Fhir.v6().Element)
    field(:_description, Fhir.v6().Element)
    field(:_experimental, Fhir.v6().Element)
    field(:_implicitRules, Fhir.v6().Element)
    field(:_language, Fhir.v6().Element)
    field(:_name, Fhir.v6().Element)
    field(:_publisher, Fhir.v6().Element)
    field(:_purpose, Fhir.v6().Element)
    field(:_status, Fhir.v6().Element)
    field(:_title, Fhir.v6().Element)
    field(:_url, Fhir.v6().Element)
    field(:_version, Fhir.v6().Element)
    field(:_versionAlgorithmString, Fhir.v6().Element)
    field(:contact, [Fhir.v6().ContactDetail], default: [])
    field(:contained, [Fhir.v6().ResourceList], default: [])
    field(:copyright, :string)
    field(:copyrightLabel, :string)
    field(:date, :datetime)
    field(:description, :string)
    field(:destination, [Fhir.v6().TestScriptDestination], default: [])
    field(:experimental, :boolean)
    field(:extension, [Fhir.v6().Extension], default: [])
    field(:fixture, [Fhir.v6().TestScriptFixture], default: [])
    field(:id, :string)
    field(:identifier, [Fhir.v6().Identifier], default: [])
    field(:implicitRules, :string)
    field(:jurisdiction, [Fhir.v6().CodeableConcept], default: [])
    field(:language, :string)
    field(:meta, Fhir.v6().Meta)
    field(:metadata, Fhir.v6().TestScriptMetadata)
    field(:modifierExtension, [Fhir.v6().Extension], default: [])
    field(:name, :string)
    field(:origin, [Fhir.v6().TestScriptOrigin], default: [])
    field(:profile, [:string], default: [])
    field(:publisher, :string)
    field(:purpose, :string)
    field(:resourceType, :string, default: "TestScript")
    field(:scope, [Fhir.v6().TestScriptScope], default: [])
    field(:setup, Fhir.v6().TestScriptSetup)
    field(:status, :string)
    field(:teardown, Fhir.v6().TestScriptTeardown)
    field(:test, [Fhir.v6().TestScriptTest], default: [])
    field(:text, Fhir.v6().Narrative)
    field(:title, :string)
    field(:url, :string)
    field(:useContext, [Fhir.v6().UsageContext], default: [])
    field(:variable, [Fhir.v6().TestScriptVariable], default: [])
    field(:version, :string)
    field(:versionAlgorithmCoding, Fhir.v6().Coding)
    field(:versionAlgorithmString, :string)
  end
end
