defmodule Fhir.v6().TestScriptAssert do
  use TypedStruct

  typedstruct do
    field(:_compareToSourceExpression, Fhir.v6().Element)
    field(:_compareToSourceId, Fhir.v6().Element)
    field(:_compareToSourcePath, Fhir.v6().Element)
    field(:_contentType, Fhir.v6().Element)
    field(:_defaultManualCompletion, Fhir.v6().Element)
    field(:_description, Fhir.v6().Element)
    field(:_direction, Fhir.v6().Element)
    field(:_expression, Fhir.v6().Element)
    field(:_headerField, Fhir.v6().Element)
    field(:_label, Fhir.v6().Element)
    field(:_minimumId, Fhir.v6().Element)
    field(:_navigationLinks, Fhir.v6().Element)
    field(:_operator, Fhir.v6().Element)
    field(:_path, Fhir.v6().Element)
    field(:_requestMethod, Fhir.v6().Element)
    field(:_requestURL, Fhir.v6().Element)
    field(:_resource, Fhir.v6().Element)
    field(:_response, Fhir.v6().Element)
    field(:_responseCode, Fhir.v6().Element)
    field(:_sourceId, Fhir.v6().Element)
    field(:_stopTestOnFail, Fhir.v6().Element)
    field(:_validateProfileId, Fhir.v6().Element)
    field(:_value, Fhir.v6().Element)
    field(:_warningOnly, Fhir.v6().Element)
    field(:compareToSourceExpression, :string)
    field(:compareToSourceId, :string)
    field(:compareToSourcePath, :string)
    field(:contentType, :string)
    field(:defaultManualCompletion, :string)
    field(:description, :string)
    field(:direction, :string)
    field(:expression, :string)
    field(:extension, [Fhir.v6().Extension], default: [])
    field(:headerField, :string)
    field(:id, :string)
    field(:label, :string)
    field(:minimumId, :string)
    field(:modifierExtension, [Fhir.v6().Extension], default: [])
    field(:navigationLinks, :boolean)
    field(:operator, :string)
    field(:path, :string)
    field(:requestMethod, :string)
    field(:requestURL, :string)
    field(:requirement, [Fhir.v6().TestScriptRequirement], default: [])
    field(:resource, :string)
    field(:response, :string)
    field(:responseCode, :string)
    field(:sourceId, :string)
    field(:stopTestOnFail, :boolean)
    field(:validateProfileId, :string)
    field(:value, :string)
    field(:warningOnly, :boolean)
  end
end
