defmodule Fhir.v6().Transport do
  use TypedStruct

  typedstruct do
    field(:_authoredOn, Fhir.v6().Element)
    field(:_completionTime, Fhir.v6().Element)
    field(:_description, Fhir.v6().Element)
    field(:_implicitRules, Fhir.v6().Element)
    field(:_instantiatesUri, Fhir.v6().Element)
    field(:_intent, Fhir.v6().Element)
    field(:_language, Fhir.v6().Element)
    field(:_lastModified, Fhir.v6().Element)
    field(:_priority, Fhir.v6().Element)
    field(:_status, Fhir.v6().Element)
    field(:authoredOn, :datetime)
    field(:basedOn, [Fhir.v6().Reference], default: [])
    field(:code, Fhir.v6().CodeableConcept)
    field(:completionTime, :datetime)
    field(:contained, [Fhir.v6().ResourceList], default: [])
    field(:currentLocation, Fhir.v6().Reference)
    field(:description, :string)
    field(:encounter, Fhir.v6().Reference)
    field(:extension, [Fhir.v6().Extension], default: [])
    field(:focus, Fhir.v6().Reference)
    field(:for, Fhir.v6().Reference)
    field(:groupIdentifier, Fhir.v6().Identifier)
    field(:history, Fhir.v6().Reference)
    field(:id, :string)
    field(:identifier, [Fhir.v6().Identifier], default: [])
    field(:implicitRules, :string)
    field(:input, [Fhir.v6().TransportInput], default: [])
    field(:instantiatesCanonical, :string)
    field(:instantiatesUri, :string)
    field(:insurance, [Fhir.v6().Reference], default: [])
    field(:intent, :string)
    field(:language, :string)
    field(:lastModified, :datetime)
    field(:location, Fhir.v6().Reference)
    field(:meta, Fhir.v6().Meta)
    field(:modifierExtension, [Fhir.v6().Extension], default: [])
    field(:note, [Fhir.v6().Annotation], default: [])
    field(:output, [Fhir.v6().TransportOutput], default: [])
    field(:owner, Fhir.v6().Reference)
    field(:partOf, [Fhir.v6().Reference], default: [])
    field(:performerType, [Fhir.v6().CodeableConcept], default: [])
    field(:priority, :string)
    field(:reason, Fhir.v6().CodeableReference)
    field(:relevantHistory, [Fhir.v6().Reference], default: [])
    field(:requestedLocation, Fhir.v6().Reference)
    field(:requester, Fhir.v6().Reference)
    field(:resourceType, :string, default: "Transport")
    field(:restriction, Fhir.v6().TransportRestriction)
    field(:status, :string)
    field(:statusReason, Fhir.v6().CodeableConcept)
    field(:text, Fhir.v6().Narrative)
  end
end
